# Generated by Django 5.2.4 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='status',
            field=models.TextField(blank=True, max_length=1, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='period',
            name='display',
            field=models.TextField(blank=True, null=True, verbose_name='standardized date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='not_after',
            field=models.DateField(blank=True, null=True, verbose_name='not after'),
        ),
        migrations.AlterField(
            model_name='period',
            name='not_before',
            field=models.DateField(blank=True, null=True, verbose_name='not before'),
        ),
    ]
