# Generated by Django 5.2 on 2025-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personname',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
