# Generated by Django 5.1.4 on 2025-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personname',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='placename',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, null=True),
        ),
    ]
