# Generated by Django 5.2.4 on 2026-05-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='status',
        ),
    ]
