# Generated by Django 5.2.4 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dmad', '0003_period_end_qualifier_period_start_qualifier_and_more_squashed_0004_alter_period_not_after_alter_period_not_before'), ('dmad', '0005_alter_period_time_mode'), ('dmad', '0006_period_imprecision'), ('dmad', '0007_alter_period_imprecision_alter_period_time_mode')]

    dependencies = [
        ('dmad', '0002_remove_period_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end_qualifier',
            field=models.CharField(blank=True, choices=[('N', 'not after'), ('E', 'exact')], default='N', max_length=1, null=True, verbose_name='not after mode'),
        ),
        migrations.AddField(
            model_name='period',
            name='start_qualifier',
            field=models.CharField(blank=True, choices=[('N', 'not before'), ('E', 'exact')], default='N', max_length=1, null=True, verbose_name='not before mode'),
        ),
        migrations.AlterField(
            model_name='period',
            name='not_after',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='period',
            name='not_before',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='period',
            name='imprecision',
            field=models.CharField(choices=[('I', 'imprecise'), ('P', 'precise')], default='I', max_length=1, verbose_name='imprecision'),
        ),
        migrations.AddField(
            model_name='period',
            name='time_mode',
            field=models.CharField(choices=[('P', 'point'), ('S', 'span')], default='P', max_length=1, verbose_name='time mode'),
        ),
    ]
