# Generated by Django 5.2 on 2025-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_personname_interim_designator'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='rework_in_gnd',
            field=models.BooleanField(default=False),
        ),
    ]
