# Generated by Django 5.2.4 on 2026-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end_qualifier',
            field=models.CharField(blank=True, choices=[('N', 'not after'), ('E', 'exact')], default='N', max_length=1, null=True, verbose_name='not after mode'),
        ),
        migrations.AddField(
            model_name='period',
            name='start_qualifier',
            field=models.CharField(blank=True, choices=[('N', 'not before'), ('E', 'exact')], default='N', max_length=1, null=True, verbose_name='not before mode'),
        ),
        migrations.AddField(
            model_name='period',
            name='time_mode',
            field=models.CharField(choices=[('S', 'span'), ('P', 'point')], default='S', max_length=1, verbose_name='time mode'),
        ),
    ]
