# Generated by Django 5.2.4 on 2026-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_period_status_alter_period_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.TextField(blank=True, choices=[('D', 'documented'), ('I', 'inferred'), ('A', 'assumed')], max_length=1, null=True, verbose_name='status'),
        ),
    ]
