# Generated by Django 5.2.4 on 2026-01-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_alter_period_display_alter_period_not_after_and_more'),
        ('dmad', '0003_alter_period_status'),
    ]

    operations = [
    ]
