# Generated by Django 5.2 on 2025-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0003_place_comment_place_rework_in_gnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
