# Generated by Django 5.2.4 on 2026-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0003_period_end_qualifier_period_start_qualifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='not_after',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='period',
            name='not_before',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
    ]
