# Generated by Django 5.2.4 on 2026-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0003_period_end_qualifier_period_start_qualifier_and_more_squashed_0004_alter_period_not_after_alter_period_not_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='time_mode',
            field=models.CharField(choices=[('S', 'span'), ('P', 'point')], default='P', max_length=1, verbose_name='time mode'),
        ),
    ]
