# Generated by Django 5.2 on 2025-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0004_place_interim_designator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
