# Generated by Django 5.2.4 on 2026-01-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0004_merge_20260116_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='assumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='period',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
    ]
