# Generated by Django 5.2 on 2025-05-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_alter_place_gnd_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGeographicAreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographicAreaCodes', to='dmad.place')),
            ],
        ),
    ]
