# Generated by Django 5.2.4 on 2026-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_period_assumed_period_inferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AlterField(
            model_name='period',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
    ]
