# Generated by Django 5.2.4 on 2026-09-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_corporation_first_editor_person_first_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='interim designator'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='raw_data',
            field=models.TextField(null=True, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='rework_in_gnd',
            field=models.BooleanField(default=False, verbose_name='rework in GND'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='interim designator'),
        ),
        migrations.AlterField(
            model_name='person',
            name='raw_data',
            field=models.TextField(null=True, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rework_in_gnd',
            field=models.BooleanField(default=False, verbose_name='rework in GND'),
        ),
        migrations.AlterField(
            model_name='place',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='place',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='interim designator'),
        ),
        migrations.AlterField(
            model_name='place',
            name='raw_data',
            field=models.TextField(null=True, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rework_in_gnd',
            field=models.BooleanField(default=False, verbose_name='rework in GND'),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='interim designator'),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='raw_data',
            field=models.TextField(null=True, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='rework_in_gnd',
            field=models.BooleanField(default=False, verbose_name='rework in GND'),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GND ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='interim designator'),
        ),
        migrations.AlterField(
            model_name='work',
            name='raw_data',
            field=models.TextField(null=True, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='work',
            name='rework_in_gnd',
            field=models.BooleanField(default=False, verbose_name='rework in GND'),
        ),
    ]
