# Generated by Django 5.2.4 on 2026-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_alter_period_time_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='imprecision',
            field=models.CharField(choices=[('P', 'precise'), ('I', 'imprecise')], default='I', max_length=1, verbose_name='imprecision'),
        ),
    ]
