# Generated by Django 5.2 on 2025-05-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0006_placegeographicareacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placegeographicareacode',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_area_codes', to='dmad.place'),
        ),
    ]
