# Generated by Django 5.2.4 on 2026-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0006_period_imprecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='imprecision',
            field=models.CharField(choices=[('I', 'imprecise'), ('P', 'precise')], default='I', max_length=1, verbose_name='imprecision'),
        ),
        migrations.AlterField(
            model_name='period',
            name='time_mode',
            field=models.CharField(choices=[('P', 'point'), ('S', 'span')], default='P', max_length=1, verbose_name='time mode'),
        ),
    ]
