# Generated by Django 5.2 on 2025-06-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0007_alter_placegeographicareacode_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='geographic_area_code',
        ),
        migrations.CreateModel(
            name='PersonGeographicAreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_area_codes', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
