# Generated by Django 5.2 on 2025-06-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0008_remove_person_geographic_area_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNDSubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTermName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(null=True)),
                ('rework_in_gnd', models.BooleanField(default=False)),
                ('gnd_id', models.CharField(blank=True, max_length=20, null=True)),
                ('gnd_subject_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.gndsubjectcategory')),
                ('parent_subjects', models.ManyToManyField(blank=True, to='dmad.subjectterm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
