# Generated by Django 5.2 on 2025-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0009_gndsubjectcategory_subjecttermname_subjectterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectterm',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectterm',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
