# Generated by Django 5.2 on 2025-06-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0010_subjectterm_comment_subjectterm_interim_designator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttermname',
            name='subjectterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='dmad.subjectterm'),
        ),
    ]
