# Generated by Django 5.2 on 2025-06-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0012_alter_gndsubjectcategory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttermname',
            name='subjectterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='dmad.subjectterm'),
        ),
    ]
