# Generated by Django 5.2 on 2025-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0014_alter_gndsubjectcategory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='interim_designator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='raw_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='rework_in_gnd',
            field=models.BooleanField(default=False),
        ),
    ]
