# Generated by Django 5.1.4 on 2025-06-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_alter_personname_status_alter_placename_status'),
        ('dmad', '0014_alter_gndsubjectcategory_link'),
    ]

    operations = [
    ]
