# Generated by Django 5.1.4 on 2025-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0015_merge_20250626_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttermname',
            old_name='subjectterm',
            new_name='subject_term',
        ),
        migrations.AlterField(
            model_name='subjecttermname',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1),
        ),
    ]
