# Generated by Django 5.2 on 2025-06-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0015_work_comment_work_gnd_id_work_interim_designator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGeographicAreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_area_codes', to='dmad.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
