# Generated by Django 5.2.4 on 2025-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0016_rename_subjectterm_subjecttermname_subject_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='display',
            field=models.TextField(blank=True, null=True),
        ),
    ]
