# Generated by Django 5.2 on 2025-06-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0016_workgeographicareacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_subject_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.gndsubjectcategory'),
        ),
        migrations.AddField(
            model_name='place',
            name='gnd_subject_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.gndsubjectcategory'),
        ),
        migrations.AddField(
            model_name='work',
            name='gnd_subject_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.gndsubjectcategory'),
        ),
    ]
