# Generated by Django 5.2 on 2025-06-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0017_person_gnd_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date_of_production',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='first_composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_composer_of', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='work',
            name='form_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_of_work_or_expression', to='dmad.subjectterm'),
        ),
        migrations.AddField(
            model_name='work',
            name='opus_or_other',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
