# Generated by Django 5.2 on 2025-07-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0016_rename_subjectterm_subjecttermname_subject_term_and_more'),
        ('dmad', '0018_work_date_of_production_work_first_composer_and_more'),
    ]

    operations = [
    ]
