# Generated by Django 5.2 on 2025-07-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0019_merge_20250702_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date_of_production',
            new_name='date_of_creation',
        ),
        migrations.AddField(
            model_name='work',
            name='broader_term',
            field=models.ManyToManyField(blank=True, to='dmad.subjectterm'),
        ),
        migrations.AlterField(
            model_name='work',
            name='form_of_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_of_work_and_expression', to='dmad.subjectterm'),
        ),
        migrations.CreateModel(
            name='WorkName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, null=True)),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='dmad.work')),
            ],
        ),
    ]
