# Generated by Django 5.2 on 2025-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0020_rename_date_of_production_work_date_of_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='broader_term',
            new_name='broader_terms',
        ),
        migrations.RemoveField(
            model_name='work',
            name='first_composer',
        ),
        migrations.AddField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='authors', to='dmad.person'),
        ),
    ]
