# Generated by Django 5.2 on 2025-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0021_rename_broader_term_work_broader_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectterm',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
