# Generated by Django 5.2 on 2025-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0022_alter_person_gnd_id_alter_place_gnd_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='broader_terms',
            field=models.ManyToManyField(blank=True, to='dmad.work'),
        ),
    ]
