# Generated by Django 5.2 on 2025-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0023_alter_work_broader_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='opus_or_other',
            new_name='opus',
        ),
        migrations.AddField(
            model_name='work',
            name='work_catalouge_number',
            field=models.CharField(null=True),
        ),
    ]
