# Generated by Django 5.2.4 on 2025-07-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0017_alter_period_display'),
        ('dmad', '0024_rename_opus_or_other_work_opus_and_more'),
    ]

    operations = [
    ]
