# Generated by Django 5.2.4 on 2025-07-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0018_corporation_corporationgeographicareacode_and_more'),
        ('dmad', '0025_merge_20250723_1325'),
    ]

    operations = [
    ]
