# Generated by Django 5.2.4 on 2025-07-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0026_merge_20250723_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='gnd_subject_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.gndsubjectcategory'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
