# Generated by Django 5.2.4 on 2025-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0027_corporation_gnd_subject_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='place',
        ),
        migrations.AddField(
            model_name='corporation',
            name='place',
            field=models.ManyToManyField(to='dmad.place'),
        ),
    ]
