# Generated by Django 5.2.4 on 2025-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0028_remove_corporation_place_corporation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='category',
        ),
        migrations.AddField(
            model_name='corporation',
            name='category',
            field=models.ManyToManyField(to='dmad.subjectterm'),
        ),
    ]
