# Generated by Django 5.2.4 on 2025-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0029_remove_corporation_category_corporation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='gnd_subject_category',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gnd_subject_category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='gnd_subject_category',
        ),
        migrations.RemoveField(
            model_name='work',
            name='gnd_subject_category',
        ),
        migrations.AddField(
            model_name='corporation',
            name='gnd_subject_category',
            field=models.ManyToManyField(to='dmad.gndsubjectcategory'),
        ),
        migrations.AddField(
            model_name='person',
            name='gnd_subject_category',
            field=models.ManyToManyField(to='dmad.gndsubjectcategory'),
        ),
        migrations.AddField(
            model_name='place',
            name='gnd_subject_category',
            field=models.ManyToManyField(to='dmad.gndsubjectcategory'),
        ),
        migrations.AddField(
            model_name='work',
            name='gnd_subject_category',
            field=models.ManyToManyField(to='dmad.gndsubjectcategory'),
        ),
    ]
