# Generated by Django 5.2.4 on 2025-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0030_remove_corporation_gnd_subject_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectterm',
            name='gnd_subject_category',
        ),
        migrations.AddField(
            model_name='subjectterm',
            name='gnd_subject_category',
            field=models.ManyToManyField(to='dmad.gndsubjectcategory'),
        ),
    ]
