# Generated by Django 5.2.4 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='professions',
            field=models.ManyToManyField(to='dmad.subjectterm'),
        ),
    ]
