services:

  redis:
    image: redis:7-alpine
    container_name: liszt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  flower:
    image: mher/flower:latest
    container_name: liszt_flower
    restart: unless-stopped
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      - redis

