# Generated by Django 5.1.4 on 2025-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zotitem',
            name='zot_short_title',
            field=models.TextField(blank=True, help_text="Stores all information from zoteros 'shortTitle' field.", verbose_name='shortTitle'),
        ),
    ]
