"""
Django settings for liszteditor project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dotenv
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_file = os.path.join(BASE_DIR, '.env')
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)
else:
    print("Could not find .env file")
    exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# App version
APP_VERSION = "0.0.1"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g562zyg%dply65c+z#rb4_eg=wr(=3u3m5=f(vp9a%lr=9%1eh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

if not DEBUG:
    ALLOWED_HOSTS.append(os.environ['DOMAIN_NAME'])

# Application definition

INSTALLED_APPS = [
    'apps.liszt_util',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'dal_select2',
    'debug_toolbar',
    'django_htmx',
    'bib',
    'django.forms',
    'dmrism.apps.DmrismConfig',
    'edwoca.apps.EdwocaConfig',
    'dmad_on_django'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dmad_on_django.middleware.HTMXPreloadCacheMiddleware'
]

ROOT_URLCONF = 'liszteditor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.liszt_util.context_processors.current_app_name',
                'apps.liszt_util.context_processors.app_version',
                'apps.edwoca.context_processors.entity_type',
            ],
        },
    },
]

WSGI_APPLICATION = 'liszteditor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'de'

LANGUAGES = [
    ('de', 'German'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
        BASE_DIR / 'static'
    ]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
        '127.0.0.1',
    ]

Z_ID = "5080468"
Z_LIBRARY_TYPE = 'group'
Z_API_KEY = os.environ['ZOTERO_API_KEY']

RISM_API_KEY = os.environ['RISM_API_KEY']

EDWOCA_FIXED_PERSONS = {
        'Liszt': '118573527',
        'zS': None,
        'Dr': None
    }

EDWOCA_FIXED_DATES = {
        'birth': {
            'day': 22,
            'month': 10,
            'year': 1811
        },
        'death': {
            'day': 31,
            'month': 7,
            'year': 1886
        }
    }

EDITOR_MODE = 'dev'

# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SIGNAL_PROCESSOR = 'bib.signals.CustomRealtimeSignalProcessor'
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index')
    },
}

GLOBAL_NAVIGATION = {
        'edwoca': {
                'label': 'edwoca',
                'href': reverse_lazy('edwoca:index')
            },
        'dmad_on_django': {
                'label': 'DMAd',
                'href': reverse_lazy('dmad_on_django:index')
            },
        'bib': {
                'label': 'Bib',
                'href': reverse_lazy('bib:index')
            },
        'musiconn': {
                'label': 'musiconn',
                'href': None
            },
        'dmrism': {
                'label': 'RISM',
                'href': reverse_lazy('dmrism:index')
            }
    }
