"""
Django settings for liszteditor project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    dot_env_path = BASE_DIR / ".env"
    if dot_env_path.is_file():
        load_dotenv(dotenv_path=dot_env_path, override=False)
except Exception:
    pass  # .env ist optional im Container

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g562zyg%dply65c+z#rb4_eg=wr(=3u3m5=f(vp9a%lr=9%1eh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

if not DEBUG:
    ALLOWED_HOSTS.append(os.environ['DOMAIN_NAME'])

# Application definition

INSTALLED_APPS = [
    'apps.liszt_util',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'dal_select2',
    'debug_toolbar',
    'django_htmx',
    'bib',
    'django.forms',
    'dmrism',
    'edwoca',
    'dmad_on_django'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dmad_on_django.middleware.HTMXPreloadCacheMiddleware'
]

ROOT_URLCONF = 'liszteditor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.liszt_util.context_processors.current_app_name',
                'apps.edwoca.context_processors.entity_type',
            ],
        },
    },
]

WSGI_APPLICATION = 'liszteditor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv('DATABASE_URL'),  
        conn_max_age=600,            
        ssl_require=False           
    )
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/0"),
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
        '127.0.0.1',
    ]

#FORM_RENDERER = 'edwoca.forms.EdwocaFormRenderer'

Z_ID = "5080468"
Z_LIBRARY_TYPE = 'group'
Z_API_KEY = os.environ['ZOTERO_API_KEY']

RISM_API_KEY = os.environ['RISM_API_KEY']

# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SIGNAL_PROCESSOR = 'bib.signals.CustomRealtimeSignalProcessor'

ELASTICSEARCH_HOSTS = os.getenv("ELASTICSEARCH_HOSTS", "http://localhost:9200")

HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.elasticsearch8_backend.Elasticsearch8SearchEngine",
        "URL": ELASTICSEARCH_HOSTS,
        "INDEX_NAME": "haystack",
        # Optional:
        # "KWARGS": {"request_timeout": 10},
    }
}


GLOBAL_NAVIGATION = {
        'edwoca': {
                'label': 'edwoca',
                'href': reverse_lazy('edwoca:index')
            },
        'dmad_on_django': {
                'label': 'DMAd',
                'href': reverse_lazy('dmad_on_django:index')
            },
        'bib': {
                'label': 'Bib',
                'href': reverse_lazy('bib:index')
            },
        'musiconn': {
                'label': 'musiconn',
                'href': None
            },
        'dmrism': {
                'label': 'RISM',
                'href': reverse_lazy('dmrism:index')
            }
    }
