# Generated by Django 5.2.4 on 2025-08-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('edwoca', '0001_initial'), ('edwoca', '0002_work_comment_alter_expressiontitle_status_and_more'), ('edwoca', '0003_expression_work_catalog_number_and_more'), ('edwoca', '0004_remove_expression_expressions_and_more'), ('edwoca', '0005_expression_comment'), ('edwoca', '0006_remove_expressiontitle_comment_and_more'), ('edwoca', '0007_rename_manifestations_manifestation_related_manifestations_and_more'), ('edwoca', '0008_item_rism_id_alter_manifestation_manifestation_type_and_more'), ('edwoca', '0009_rename_history_item_location'), ('edwoca', '0010_itemcontributor'), ('edwoca', '0011_item_comment'), ('edwoca', '0012_rename_comment_expression_private_comment_and_more'), ('edwoca', '0013_alter_manifestationtitle_options_and_more'), ('edwoca', '0014_alter_manifestationbib_manifestation_and_more'), ('edwoca', '0015_manifestation_is_singleton'), ('edwoca', '0016_library_remove_manifestation_rism_id_signature'), ('edwoca', '0017_alter_signature_signature'), ('edwoca', '0018_alter_library_name_alter_signature_signature'), ('edwoca', '0019_rename_role_signature_status_signature_item_and_more'), ('edwoca', '0020_alter_item_rism_id_alter_signature_signature'), ('edwoca', '0021_manifestation_missing_item_and_more'), ('edwoca', '0022_remove_item_rism_id_manifestation_rism_id_and_more'), ('edwoca', '0013_alter_expressioncontributor_person_and_more'), ('edwoca', '0023_merge_20250723_1325'), ('edwoca', '0024_remove_item_manifestation_and_more')]

    initial = True

    dependencies = [
        ('bib', '0001_initial'),
        ('dmad', '0002_alter_personname_status_alter_placename_status'),
        ('dmad', '0016_rename_subjectterm_subjecttermname_subject_term_and_more'),
        ('dmad', '0019_merge_20250702_0851'),
        ('dmad', '__first__'),
        ('dmrism', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incipit_music', models.TextField()),
                ('incipit_text', models.TextField()),
                ('period_comment', models.TextField()),
                ('history', models.TextField()),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expression', to='dmad.period')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.expression')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.ExpressionContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnd_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('work_catalog_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('related_work', models.ManyToManyField(through='edwoca.RelatedWork', to='edwoca.work')),
            ],
            options={
                'ordering': ['work_catalog_number'],
            },
        ),
        migrations.AddField(
            model_name='relatedwork',
            name='source_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_work_of', to='edwoca.work'),
        ),
        migrations.AddField(
            model_name='relatedwork',
            name='target_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_work_of', to='edwoca.work'),
        ),
        migrations.AddField(
            model_name='expression',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='edwoca.work'),
        ),
        migrations.CreateModel(
            name='WorkBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='bib',
            field=models.ManyToManyField(through='edwoca.WorkBib', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='WorkContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.WorkContributor', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='work',
            name='private_comment',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1)),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.work')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='work_catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Metronom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_value', models.CharField(choices=[('1/8', '1/8'), ('1/4', '1/4'), ('1/4.', '1/4.'), ('1/2', '1/2'), ('1/2.', '1/2.')], default='1/4', max_length=4)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metronom', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('meter', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'e'), ('F', 'F'), ('G', 'G')], default='C', max_length=1)),
                ('accidental', models.CharField(choices=[('', ''), ('#', '#'), ('##', '##'), ('b', 'b'), ('bb', 'bb')], default='', max_length=2)),
                ('mode', models.CharField(choices=[('MA', 'Major'), ('MI', 'Minor')], default='MA', max_length=2)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='edwoca.movement')),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='manifestations',
            field=models.ManyToManyField(to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='IndexNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('RAABE', 'Raabe'), ('MULLER', 'Müller/Eckhardt'), ('SEARLE', 'Searle'), ('CHIAPPARI', 'Chiappari')], default='RAABE', max_length=10)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_numbers', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2)),
                ('source_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_expression_of', to='edwoca.expression')),
                ('target_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_expression_of', to='edwoca.expression')),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='related_expressions',
            field=models.ManyToManyField(through='edwoca.RelatedExpression', to='edwoca.expression'),
        ),
        migrations.AddField(
            model_name='expression',
            name='private_comment',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ExpressionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1)),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.expression')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PUB', 'Published')], default='PUB', max_length=10)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.place')),
            ],
        ),
        migrations.CreateModel(
            name='EventContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.EventContributor', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='expression',
            name='public_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='public_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expressioncontributor',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.expression'),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='workbib',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='expressioncontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
    ]
