# Generated by Django 5.2.4 on 2026-01-28 21:17

import django.db.models.deletion
import edwoca.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bib', '__first__'),
        ('dmad', '0001_initial'),
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('label', models.CharField(choices=[('PA', 'is part of'), ('DE', 'is derivative of'), ('SU', 'is successor of'), ('IN', 'is inspired by'), ('EX', 'uses expression of'), ('AC', 'accompanies or complements')], default='PA', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(edwoca.models.base.EdwocaUpdateUrlMixin, 'dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(edwoca.models.base.EdwocaUpdateUrlMixin, 'dmrism.item'),
        ),
        migrations.CreateModel(
            name='ManifestationTitle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dmrism.manifestationtitle',),
        ),
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, null=True)),
                ('private_head_comment', models.TextField(blank=True, null=True, verbose_name='private head comment')),
                ('private_relations_comment', models.TextField(blank=True, null=True)),
                ('private_title_comment', models.TextField(blank=True, null=True)),
                ('private_history_comment', models.TextField(blank=True, null=True)),
                ('rism_id', models.CharField(blank=True, max_length=20, null=True)),
                ('public_provenance_comment', models.TextField(blank=True, null=True)),
                ('extent', models.TextField(blank=True, null=True)),
                ('measure', models.TextField(blank=True, null=True)),
                ('private_manuscript_comment', models.TextField(blank=True, null=True)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period')),
                ('places', models.ManyToManyField(to='dmad.place')),
            ],
        ),
        migrations.CreateModel(
            name='CompositeBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='edwoca.composite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompositeBibRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.composite')),
            ],
        ),
        migrations.AddField(
            model_name='composite',
            name='bib',
            field=models.ManyToManyField(related_name='composites', through='edwoca.CompositeBibRelation', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='CompositeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status')),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.composite')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PUB', 'Published')], default='PUB', max_length=10)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.place')),
            ],
        ),
        migrations.CreateModel(
            name='EventContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.EventContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(db_index=True, default=0, verbose_name='Sortier-Index')),
                ('public_comment', models.TextField(blank=True, null=True, verbose_name='public comment')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('work_catalog_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='work catalog number')),
                ('incipit_music', models.TextField(verbose_name='incipit music')),
                ('incipit_text', models.TextField(verbose_name='incipit text')),
                ('period_comment', models.TextField(verbose_name='period comment')),
                ('history', models.TextField(verbose_name='history')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expression', to='dmad.period')),
            ],
            options={
                'ordering': ['work', 'order_index'],
            },
            bases=(edwoca.models.base.EdwocaUpdateUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExpressionContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.expression')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.ExpressionContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='ExpressionCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.expression')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressionPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.expression')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status')),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.expression')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('RAABE', 'Raabe'), ('MULLER', 'Müller/Eckhardt'), ('SEARLE', 'Searle'), ('CHIAPPARI', 'Chiappari'), ('LQWV', 'LQWV')], default='LQWV', max_length=10, verbose_name='index')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='number')),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_numbers', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='dmrism.item')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification', to='dmad.period')),
                ('related_expression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relating_modifications', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Sketch'), ('L', 'Letter'), ('P', 'Postcard'), ('C', 'Copy')], default='L', max_length=1, verbose_name='category')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('corporation_provenance', models.ManyToManyField(related_name='letters', to='dmrism.corporationprovenancestation')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter', to='dmad.period')),
                ('person_provenance', models.ManyToManyField(related_name='letters', to='dmrism.personprovenancestation')),
                ('receiver_corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_letters', to='dmad.corporation')),
                ('receiver_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_letters', to='dmad.person')),
                ('receiver_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_letters', to='dmad.place')),
                ('sender_corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_letters', to='dmad.corporation')),
                ('sender_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_letters', to='dmad.person')),
                ('sender_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_letters', to='dmad.place')),
            ],
            options={
                'ordering': ['period__not_before'],
            },
        ),
        migrations.CreateModel(
            name='LetterDigitalCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.TextField(blank=True, choices=[('Dig', 'Digitized'), ('IIIF', 'IIIF Manifest'), ('Prv', 'Private')], default='Dig', max_length=20, null=True, verbose_name='link type')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_copies', to='edwoca.letter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterMentioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(blank=True, max_length=20, null=True, verbose_name='pages')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.letter')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='edition',
            field=models.ManyToManyField(related_name='edited_letters', through='edwoca.LetterMentioning', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='Metronom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_value', models.CharField(choices=[('1/8', '1/8'), ('1/4', '1/4'), ('1/4.', '1/4.'), ('1/2', '1/2'), ('1/2.', '1/2.')], default='1/4', max_length=4, verbose_name='reference value')),
                ('bpm', models.IntegerField(blank=True, null=True, verbose_name='bpm')),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metronom', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationHandwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='medium')),
                ('dubious_writer', models.BooleanField(default=False, verbose_name='dubious writer')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='edwoca.itemmodification')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='title')),
                ('tempo', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='tempo')),
                ('meter', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='meter')),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'e'), ('F', 'F'), ('G', 'G')], default='C', max_length=1, verbose_name='note')),
                ('accidental', models.CharField(choices=[('', ''), ('#', '#'), ('##', '##'), ('b', 'b'), ('bb', 'bb')], default='', max_length=2, verbose_name='accidental')),
                ('mode', models.CharField(choices=[('MA', 'Major'), ('MI', 'Minor')], default='MA', max_length=2, verbose_name='mode')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='edwoca.movement')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('label', models.CharField(choices=[('CP', 'is componnt of'), ('PA', 'is part of'), ('DE', 'is derivative of'), ('IN', 'is incorporated in'), ('AL', 'has alternative')], default='PA', max_length=2, verbose_name='label')),
                ('source_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_expression_of', to='edwoca.expression')),
                ('target_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_expression_of', to='edwoca.expression')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='related_expressions',
            field=models.ManyToManyField(through='edwoca.RelatedExpression', to='edwoca.expression'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_comment', models.TextField(blank=True, null=True, verbose_name='public comment')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('gnd_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('work_catalog_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('private_head_comment', models.TextField(blank=True, null=True, verbose_name='private head comment')),
                ('related_work', models.ManyToManyField(through='edwoca.RelatedWork', to='edwoca.work')),
            ],
            options={
                'ordering': ['work_catalog_number'],
            },
            bases=(edwoca.models.base.EdwocaUpdateUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubjectTermWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.subjectterm')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='relatedwork',
            name='source_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_work_of', to='edwoca.work'),
        ),
        migrations.AddField(
            model_name='relatedwork',
            name='target_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_work_of', to='edwoca.work'),
        ),
        migrations.CreateModel(
            name='PlaceWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='work',
            field=models.ManyToManyField(related_name='letters', to='edwoca.work'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='related_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relating_modifications', to='edwoca.work'),
        ),
        migrations.AddField(
            model_name='expression',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='edwoca.work'),
        ),
        migrations.CreateModel(
            name='CorporationWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.corporation')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='work',
            name='bib',
            field=models.ManyToManyField(through='edwoca.WorkBib', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='WorkContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='work',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.WorkContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='WorkCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status')),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.work')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.work')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='manifestation',
            field=models.ManyToManyField(related_name='letters', to='edwoca.manifestation'),
        ),
        migrations.AddField(
            model_name='expression',
            name='manifestations',
            field=models.ManyToManyField(related_name='expressions', to='edwoca.manifestation'),
        ),
        migrations.CreateModel(
            name='CompositeManifestationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.composite')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.manifestation')),
            ],
        ),
        migrations.AddField(
            model_name='composite',
            name='manifestations',
            field=models.ManyToManyField(related_name='composites', through='edwoca.CompositeManifestationRelation', to='edwoca.manifestation'),
        ),
        migrations.CreateModel(
            name='CompositeItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.composite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.item')),
            ],
        ),
        migrations.AddField(
            model_name='composite',
            name='items',
            field=models.ManyToManyField(related_name='composites', through='edwoca.CompositeItemRelation', to='edwoca.item'),
        ),
        migrations.CreateModel(
            name='LetterSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=20, null=True, verbose_name='signature')),
                ('status', models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1, verbose_name='status')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='edwoca.letter')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library', verbose_name='holding institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('letter',), name='unique_current_letter_signature')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('work', 'order_index')},
        ),
    ]
