# Generated by Django 5.2.4 on 2025-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
        ('edwoca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='corporation_provenance',
            field=models.ManyToManyField(related_name='letters', to='dmrism.corporationprovenancestation'),
        ),
        migrations.AddField(
            model_name='letter',
            name='item',
            field=models.ManyToManyField(related_name='letters', to='edwoca.item'),
        ),
        migrations.AddField(
            model_name='letter',
            name='manifestation',
            field=models.ManyToManyField(related_name='letters', to='edwoca.manifestation'),
        ),
        migrations.AddField(
            model_name='letter',
            name='person_provenance',
            field=models.ManyToManyField(related_name='letters', to='dmrism.personprovenancestation'),
        ),
    ]
