# Generated by Django 5.2.4 on 2026-06-01 14:16

import django.db.models.deletion
from django.db import migrations, models


def migrate_partlabel(apps, schema_editor):
    Manifestation = apps.get_model('edwoca', 'manifestation')

    Manifestation.objects.filter(part_label = 'c').update(part_label = 'j')
    Manifestation.objects.filter(part_label = 'b').update(part_label = 'j')


def migrate_completeness(apps, schema_editor):
    Manifestation = apps.get_model('edwoca', 'manifestation')

    Manifestation.objects.filter(manifestation_form = 'EX').update(completeness = 'i')

    for m in Manifestation.objects.filter(manifestation_form = 'FR'):
        m.private_comment = m.private_comment + '\nFragment'
        m.needs_review = True
        m.save()

    Manifestation.objects.filter(manifestation_form = 'EX').update(manifestation_form = None)
    Manifestation.objects.filter(manifestation_form = 'FR').update(manifestation_form = None)



class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('edwoca', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_partlabel, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_completeness, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='DocumentedEntityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-needs_review', 'edition_period__not_before']},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='manifestation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='period',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_corporation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_person',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_place',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_corporation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_person',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_place',
        ),
        migrations.RemoveField(
            model_name='lettermentioning',
            name='pages',
        ),
        migrations.AddField(
            model_name='letter',
            name='diplomatic_source_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='diplomatic date on source'),
        ),
        migrations.AddField(
            model_name='letter',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_date_for_letter', to='dmad.period'),
        ),
        migrations.AddField(
            model_name='letter',
            name='expression',
            field=models.ManyToManyField(related_name='letters', to='edwoca.expression'),
        ),
        migrations.AddField(
            model_name='letter',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
        ),
        migrations.AddField(
            model_name='letter',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AddField(
            model_name='letter',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
        migrations.AddField(
            model_name='letter',
            name='mentioned_works',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='letter',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_edition_corporation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='sender corporation name according to edition'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_source_corporation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='sender corporation name according to source'),
        ),
        migrations.AddField(
            model_name='letter',
            name='source_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period'),
        ),
        migrations.AddField(
            model_name='letter',
            name='work_mentionings',
            field=models.TextField(blank=True, null=True, verbose_name='work mentionings'),
        ),
        migrations.AddField(
            model_name='lettermentioning',
            name='letter_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='letter number'),
        ),
        migrations.AddField(
            model_name='lettermentioning',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='bib location'),
        ),
        migrations.AddField(
            model_name='lettermentioning',
            name='location_type',
            field=models.CharField(choices=[('P', 'page'), ('C', 'column'), ('L', 'lot')], default='P', max_length=1, verbose_name='bib location type'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='sorting index'),
        ),
        migrations.AlterField(
            model_name='letterdigitalcopy',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='lettersignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='relatedexpression',
            name='label',
            field=models.CharField(choices=[('CP', 'is component of'), ('PA', 'is part of'), ('DE', 'is derivative of'), ('IN', 'is incorporated in'), ('AL', 'has alternative')], default='PA', max_length=2, verbose_name='label'),
        ),
        migrations.CreateModel(
            name='ReceiverCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_corporations',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverCorporation', to='dmad.corporation', verbose_name='receiver corporation'),
        ),
        migrations.CreateModel(
            name='ReceiverPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.person')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_persons',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverPerson', to='dmad.person', verbose_name='receiver person'),
        ),
        migrations.CreateModel(
            name='ReceiverPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.place')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_places',
            field=models.ManyToManyField(related_name='receiver_place_of', through='edwoca.ReceiverPlace', to='dmad.place', verbose_name='receiver place'),
        ),
        migrations.CreateModel(
            name='SenderCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_corporations',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderCorporation', to='dmad.corporation', verbose_name='sender corporation'),
        ),
        migrations.CreateModel(
            name='SenderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.person')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_persons',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderPerson', to='dmad.person', verbose_name='sender person'),
        ),
        migrations.CreateModel(
            name='SenderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('edition_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.place')),
                ('source_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_places',
            field=models.ManyToManyField(related_name='sender_place_of', through='edwoca.SenderPlace', to='dmad.place', verbose_name='sender place'),
        ),
    ]
