# Generated by Django 5.2.4 on 2026-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='signature'),
            preserve_default=False,
        ),
    ]
