# Generated by Django 5.2.4 on 2025-08-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_alter_manifestation_edition_type'),
        ('edwoca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestationTitle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dmrism.manifestationtitle',),
        ),
    ]
