# Generated by Django 5.2.4 on 2025-10-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_letter_corporation_provenance_letter_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='item',
        ),
    ]
