# Generated by Django 5.2.4 on 2025-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_remove_itemmodification_modification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='work',
            field=models.ManyToManyField(related_name='letters', to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='relatedexpression',
            name='label',
            field=models.CharField(choices=[('CP', 'is componnt of'), ('PA', 'is part of'), ('DE', 'is derivative of'), ('IN', 'is incorporated in'), ('AL', 'has alternative')], default='PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='relatedwork',
            name='label',
            field=models.CharField(choices=[('PA', 'is part of'), ('DE', 'is derivative of'), ('SU', 'is successor of'), ('IN', 'is inspired by'), ('EX', 'uses expression of'), ('AC', 'accompanies or complements')], default='PA', max_length=2),
        ),
    ]
