# Generated by Django 5.1.4 on 2025-05-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_work_comment_alter_expressiontitle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='work_catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expressiontitle',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expressiontitle',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expressiontitle',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Metronom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_value', models.CharField(choices=[('1/8', '1/8'), ('1/4', '1/4'), ('1/4.', '1/4.'), ('1/2', '1/2'), ('1/2.', '1/2.')], default='1/4', max_length=4)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metronom', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('meter', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'e'), ('F', 'F'), ('G', 'G')], default='C', max_length=1)),
                ('accidental', models.CharField(choices=[('', ''), ('#', '#'), ('##', '##'), ('b', 'b'), ('bb', 'bb')], default='', max_length=2)),
                ('mode', models.CharField(choices=[('MA', 'Major'), ('MI', 'Minor')], default='MA', max_length=2)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='edwoca.movement')),
            ],
        ),
    ]
