# Generated by Django 5.2.4 on 2026-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_documentedentityname_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='manifestation',
            field=models.ManyToManyField(related_name='letters', to='edwoca.manifestation'),
        ),
    ]
