# Generated by Django 5.2.4 on 2026-05-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_documentedentityname_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-needs_review', 'edition_period__not_before']},
        ),
    ]
