# Generated by Django 5.2.4 on 2026-04-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0002_alter_lettersignature_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='sorting index'),
        ),
    ]
