# Generated by Django 5.2.4 on 2025-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0003_letter_work_alter_relatedexpression_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='private_head_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
