# Generated by Django 5.2.4 on 2026-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0003_alter_letter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='signature'),
        ),
    ]
