# Generated by Django 5.1.4 on 2025-05-20 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0003_expression_work_catalog_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='expressions',
        ),
        migrations.AddField(
            model_name='expression',
            name='manifestations',
            field=models.ManyToManyField(to='edwoca.manifestation'),
        ),
        migrations.CreateModel(
            name='IndexNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('RAABE', 'Raabe'), ('MULLER', 'Müller/Eckhardt'), ('SEARLE', 'Searle'), ('CHIAPPARI', 'Chiappari')], default='RAABE', max_length=10)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_numbers', to='edwoca.expression')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2)),
                ('source_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_expression_of', to='edwoca.expression')),
                ('target_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_expression_of', to='edwoca.expression')),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='related_expressions',
            field=models.ManyToManyField(through='edwoca.RelatedExpression', to='edwoca.expression'),
        ),
    ]
