# Generated by Django 5.2.4 on 2026-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0003_letter_manifestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='item',
            field=models.ManyToManyField(related_name='letters', to='edwoca.item'),
        ),
    ]
