# Generated by Django 5.2.4 on 2026-04-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('edwoca', '0003_alter_expression_order_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentedEntityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['edition_period__not_before']},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='manifestation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='period',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_corporation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_person',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_corporation',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_person',
        ),
        migrations.AddField(
            model_name='letter',
            name='diplomatic_source_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='diplomatic date on source'),
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_date_for_letter', to='dmad.period'),
        ),
        migrations.AddField(
            model_name='letter',
            name='expression',
            field=models.ManyToManyField(related_name='letters', to='edwoca.expression'),
        ),
        migrations.AddField(
            model_name='letter',
            name='mentioned_works',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='letter',
            name='source_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period'),
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver_place',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_place',
        ),
        migrations.AlterField(
            model_name='relatedexpression',
            name='label',
            field=models.CharField(choices=[('CP', 'is component of'), ('PA', 'is part of'), ('DE', 'is derivative of'), ('IN', 'is incorporated in'), ('AL', 'has alternative')], default='PA', max_length=2, verbose_name='label'),
        ),
        migrations.CreateModel(
            name='EditionReceiverCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_receiver_corporation',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.EditionReceiverCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='EditionReceiverPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('edition_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_receiver_person',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.EditionReceiverPerson', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='EditionSenderCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_sender_corporation',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.EditionSenderCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='EditionSenderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('edition_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='edition_sender_person',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.EditionSenderPerson', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='ReceiverPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.place')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.place')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceReceiverCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='source_receiver_corporation',
            field=models.ManyToManyField(related_name='source_receiver_of', through='edwoca.SourceReceiverCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='SourceReceiverPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='source_receiver_person',
            field=models.ManyToManyField(related_name='source_receiver_of', through='edwoca.SourceReceiverPerson', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='SourceSenderCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='source_sender_corporation',
            field=models.ManyToManyField(related_name='source_sender_of', through='edwoca.SourceSenderCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='SourceSenderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='source_sender_person',
            field=models.ManyToManyField(related_name='source_sender_of', through='edwoca.SourceSenderPerson', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_place',
            field=models.ManyToManyField(related_name='receiver_place_of', through='edwoca.ReceiverPlace', to='dmad.place'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_place',
            field=models.ManyToManyField(related_name='sender_place_of', through='edwoca.SenderPlace', to='dmad.place'),
        ),
    ]
