# Generated by Django 5.2.4 on 2025-10-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0032_person_professions'),
        ('edwoca', '0003_remove_letter_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexnumber',
            name='index',
            field=models.CharField(choices=[('RAABE', 'Raabe'), ('MULLER', 'Müller/Eckhardt'), ('SEARLE', 'Searle'), ('CHIAPPARI', 'Chiappari'), ('LQWV', 'LQWV')], default='LQWV', max_length=10),
        ),
        migrations.CreateModel(
            name='CorporationWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.corporation')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectTermWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.subjectterm')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencing_works', to='dmad.work')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
