# Generated by Django 5.2.4 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0004_documentedentityname_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='signature'),
        ),
    ]
