# Generated by Django 5.2.4 on 2025-11-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0004_alter_indexnumber_index_corporationworkreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='personworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='placeworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='subjecttermworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='workworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
    ]
