# Generated by Django 5.2.4 on 2025-11-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0032_person_professions'),
        ('dmrism', '0002_item_rism_id'),
        ('edwoca', '0004_alter_indexnumber_index_corporationworkreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='personworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='placeworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='subjecttermworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.AlterField(
            model_name='workworkreference',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work'),
        ),
        migrations.CreateModel(
            name='ItemModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('modification_type', models.CharField(choices=[('AR', 'Arrangement'), ('TR', 'Transcription'), ('RV', 'Revision')], default=None, max_length=2, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='dmrism.item')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification', to='dmad.period')),
                ('related_expression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relating_modifications', to='edwoca.expression')),
                ('related_manifestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relating_modifications', to='dmrism.manifestation')),
                ('related_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relating_modifications', to='edwoca.work')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationHandwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('dubious_writer', models.BooleanField(default=False)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='edwoca.itemmodification')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
