# Generated by Django 5.2.4 on 2026-08-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0004_letter_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodification',
            name='collection_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='edwoca.manifestation'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='modification_description',
            field=models.TextField(blank=True, null=True, verbose_name='description of modification'),
        ),
    ]
