# Generated by Django 5.2.4 on 2026-01-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_alter_item_extent_alter_item_measure_and_more'),
        ('edwoca', '0004_work_private_head_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['period__not_before']},
        ),
        migrations.AlterField(
            model_name='composite',
            name='private_head_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private head comment'),
        ),
        migrations.AlterField(
            model_name='compositetitle',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='compositetitle',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='compositetitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='history',
            field=models.TextField(verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='incipit_music',
            field=models.TextField(verbose_name='incipit music'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='incipit_text',
            field=models.TextField(verbose_name='incipit text'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='period_comment',
            field=models.TextField(verbose_name='period comment'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='private_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private comment'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='public_comment',
            field=models.TextField(blank=True, null=True, verbose_name='public comment'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='work_catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='work catalog number'),
        ),
        migrations.AlterField(
            model_name='expressioncontributor',
            name='role',
            field=models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='expressioncorporationdedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='expressionpersondedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='expressiontitle',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='expressiontitle',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='expressiontitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='indexnumber',
            name='index',
            field=models.CharField(choices=[('RAABE', 'Raabe'), ('MULLER', 'Müller/Eckhardt'), ('SEARLE', 'Searle'), ('CHIAPPARI', 'Chiappari'), ('LQWV', 'LQWV')], default='LQWV', max_length=10, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='indexnumber',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='itemmodification',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='key',
            name='accidental',
            field=models.CharField(choices=[('', ''), ('#', '#'), ('##', '##'), ('b', 'b'), ('bb', 'bb')], default='', max_length=2, verbose_name='accidental'),
        ),
        migrations.AlterField(
            model_name='key',
            name='mode',
            field=models.CharField(choices=[('MA', 'Major'), ('MI', 'Minor')], default='MA', max_length=2, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='key',
            name='note',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'e'), ('F', 'F'), ('G', 'G')], default='C', max_length=1, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='category',
            field=models.CharField(choices=[('S', 'Sketch'), ('L', 'Letter'), ('P', 'Postcard'), ('C', 'Copy')], default='L', max_length=1, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='letterdigitalcopy',
            name='link_type',
            field=models.TextField(blank=True, choices=[('Dig', 'Digitized'), ('IIIF', 'IIIF Manifest'), ('Prv', 'Private')], default='Dig', max_length=20, null=True, verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='letterdigitalcopy',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='lettermentioning',
            name='pages',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='lettersignature',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library'),
        ),
        migrations.AlterField(
            model_name='lettersignature',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='lettersignature',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='metronom',
            name='bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='bpm'),
        ),
        migrations.AlterField(
            model_name='metronom',
            name='reference_value',
            field=models.CharField(choices=[('1/8', '1/8'), ('1/4', '1/4'), ('1/4.', '1/4.'), ('1/2', '1/2'), ('1/2.', '1/2.')], default='1/4', max_length=4, verbose_name='reference value'),
        ),
        migrations.AlterField(
            model_name='modificationhandwriting',
            name='dubious_writer',
            field=models.BooleanField(default=False, verbose_name='dubious writer'),
        ),
        migrations.AlterField(
            model_name='modificationhandwriting',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='meter',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='meter'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='tempo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='tempo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='relatedexpression',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='relatedexpression',
            name='label',
            field=models.CharField(choices=[('CP', 'is componnt of'), ('PA', 'is part of'), ('DE', 'is derivative of'), ('IN', 'is incorporated in'), ('AL', 'has alternative')], default='PA', max_length=2, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relatedwork',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='private_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='private_head_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private head comment'),
        ),
        migrations.AlterField(
            model_name='work',
            name='public_comment',
            field=models.TextField(blank=True, null=True, verbose_name='public comment'),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='role',
            field=models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='workcorporationdedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='workpersondedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
