# Generated by Django 5.2.4 on 2026-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0004_alter_lettersignature_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettermentioning',
            name='pages',
        ),
        migrations.AddField(
            model_name='lettermentioning',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='bib location'),
        ),
        migrations.AddField(
            model_name='lettermentioning',
            name='location_type',
            field=models.CharField(choices=[('P', 'page'), ('C', 'column'), ('L', 'lot')], default='P', max_length=1, verbose_name='bib location type'),
        ),
    ]
