# Generated by Django 5.2.4 on 2026-09-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0005_itemmodification_collection_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterWorkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(blank=True, null=True)),
                ('entstehung', models.BooleanField(default=False)),
                ('source_transfer', models.BooleanField(default=False)),
                ('work_catalogue_number', models.TextField(blank=True, null=True)),
                ('work_title', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_references', to='edwoca.letter')),
            ],
        ),
    ]
