# Generated by Django 5.2.4 on 2025-11-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0032_person_professions'),
        ('edwoca', '0005_alter_corporationworkreference_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationhandwriting',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='edwoca.itemmodification'),
        ),
        migrations.CreateModel(
            name='ExpressionCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.expression')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressionPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.expression')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
