# Generated by Django 5.2.4 on 2026-01-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_alter_itemsignature_library_and_more'),
        ('edwoca', '0005_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersignature',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library', verbose_name='holding institution'),
        ),
    ]
