# Generated by Django 5.2.4 on 2026-05-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('edwoca', '0005_alter_lettersignature_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editionreceiverperson',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='editionreceiverperson',
            name='edition_person',
        ),
        migrations.RemoveField(
            model_name='editionreceiverperson',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='editionreceiverperson',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='edition_receiver_person',
        ),
        migrations.RemoveField(
            model_name='editionsendercorporation',
            name='edition_corporation',
        ),
        migrations.RemoveField(
            model_name='editionsendercorporation',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='editionsendercorporation',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='editionsendercorporation',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='editionsenderperson',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='editionsenderperson',
            name='edition_person',
        ),
        migrations.RemoveField(
            model_name='editionsenderperson',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='editionsenderperson',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='sourcereceivercorporation',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='sourcereceivercorporation',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='sourcereceivercorporation',
            name='source_corporation',
        ),
        migrations.RemoveField(
            model_name='sourcereceivercorporation',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='source_receiver_corporation',
        ),
        migrations.RemoveField(
            model_name='sourcereceiverperson',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='sourcereceiverperson',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='sourcereceiverperson',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='sourcereceiverperson',
            name='source_person',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='source_receiver_person',
        ),
        migrations.RemoveField(
            model_name='sourcesendercorporation',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='sourcesendercorporation',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='sourcesendercorporation',
            name='source_corporation',
        ),
        migrations.RemoveField(
            model_name='sourcesendercorporation',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='source_sender_corporation',
        ),
        migrations.RemoveField(
            model_name='sourcesenderperson',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='sourcesenderperson',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='sourcesenderperson',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='sourcesenderperson',
            name='source_person',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='source_sender_person',
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_edition_corporation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='sender corporation name according to edition'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_source_corporation_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='sender corporation name according to source'),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='edition_name_assumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='edition_name_inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='source_name_assumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='source_name_inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='edition_name_assumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='edition_name_inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='source_name_assumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='source_name_inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReceiverCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name_inferred', models.BooleanField(default=False)),
                ('edition_name_assumed', models.BooleanField(default=False)),
                ('source_name_inferred', models.BooleanField(default=False)),
                ('source_name_assumed', models.BooleanField(default=False)),
                ('edition_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='letter',
            name='edition_receiver_corporation',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='ReceiverPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name_inferred', models.BooleanField(default=False)),
                ('edition_name_assumed', models.BooleanField(default=False)),
                ('source_name_inferred', models.BooleanField(default=False)),
                ('source_name_assumed', models.BooleanField(default=False)),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_person',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverPerson', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='SenderCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name_inferred', models.BooleanField(default=False)),
                ('edition_name_assumed', models.BooleanField(default=False)),
                ('source_name_inferred', models.BooleanField(default=False)),
                ('source_name_assumed', models.BooleanField(default=False)),
                ('edition_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.corporation')),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='letter',
            name='edition_sender_corporation',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderCorporation', to='dmad.corporation'),
        ),
        migrations.CreateModel(
            name='SenderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name_inferred', models.BooleanField(default=False)),
                ('edition_name_assumed', models.BooleanField(default=False)),
                ('source_name_inferred', models.BooleanField(default=False)),
                ('source_name_assumed', models.BooleanField(default=False)),
                ('edition_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='edwoca.letter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmad.person')),
                ('source_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='letter',
            name='edition_sender_person',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderPerson', to='dmad.person'),
        ),
        migrations.DeleteModel(
            name='EditionReceiverCorporation',
        ),
        migrations.DeleteModel(
            name='EditionReceiverPerson',
        ),
        migrations.DeleteModel(
            name='EditionSenderCorporation',
        ),
        migrations.DeleteModel(
            name='EditionSenderPerson',
        ),
        migrations.DeleteModel(
            name='SourceReceiverCorporation',
        ),
        migrations.DeleteModel(
            name='SourceReceiverPerson',
        ),
        migrations.DeleteModel(
            name='SourceSenderCorporation',
        ),
        migrations.DeleteModel(
            name='SourceSenderPerson',
        ),
    ]
