# Generated by Django 5.2.4 on 2026-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0005_itemmodification_collection_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodification',
            name='is_addition',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_note',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_title',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
    ]
