# Generated by Django 5.2.4 on 2025-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0005_alter_corporationworkreference_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expression',
            options={'ordering': ['work', 'order_index']},
        ),
        migrations.AddField(
            model_name='expression',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortier-Index'),
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('work', 'order_index')},
        ),
    ]
