# Generated by Django 5.2.4 on 2026-10-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0005_itemmodification_collection_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodification',
            name='is_title',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_addition',
            field=models.BooleanField(default=False, verbose_name='addition'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='correction'),
        ),
        migrations.AddField(
            model_name='itemmodification',
            name='is_note',
            field=models.BooleanField(default=False, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='itemmodification',
            name='collection_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='dmrism.relatedexpression'),
        ),
    ]
