# Generated by Django 5.2.4 on 2026-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0005_remove_lettermentioning_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettermentioning',
            name='letter_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
