# Generated by Django 5.1.4 on 2025-05-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
        ('dmad', '0002_alter_personname_status_alter_placename_status'),
        ('edwoca', '0006_remove_expressiontitle_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifestation',
            old_name='manifestations',
            new_name='related_manifestations',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(choices=[('PR', 'Piano Reduction'), ('SC', 'Score')], default='SC', max_length=10),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='manifestation_type',
            field=models.CharField(choices=[('MS', 'Parent'), ('RE', 'Related')], default='MS', max_length=10),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='state',
            field=models.CharField(choices=[('CP', 'complete')], default='CP', max_length=10),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PUB', 'Published')], default='PUB', max_length=10)),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.place')),
            ],
        ),
        migrations.CreateModel(
            name='EventContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contributors',
            field=models.ManyToManyField(through='edwoca.EventContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='ManifestationBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.manifestation')),
            ],
        ),
        migrations.AddField(
            model_name='manifestation',
            name='bib',
            field=models.ManyToManyField(through='edwoca.ManifestationBib', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='ManifestationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=1)),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default='German', max_length=15)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='edwoca.manifestation')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
