# Generated by Django 5.2.4 on 2026-01-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0006_alter_expression_order_index'),
        ('edwoca', '0006_alter_lettersignature_library'),
    ]

    operations = [
    ]
