# Generated by Django 5.2.4 on 2026-05-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0006_remove_editionreceiverperson_edition_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='edition_receiver_corporation',
            new_name='receiver_corporations',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='receiver_person',
            new_name='receiver_persons',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='receiver_place',
            new_name='receiver_places',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='edition_sender_corporation',
            new_name='sender_corporations',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='edition_sender_person',
            new_name='sender_persons',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='sender_place',
            new_name='sender_places',
        ),
    ]
