# Generated by Django 5.2.4 on 2026-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0006_lettermentioning_letter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivercorporation',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='receivercorporation',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
        migrations.AddField(
            model_name='receiverperson',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='receiverperson',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='receiverplace',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
        migrations.AddField(
            model_name='sendercorporation',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='sendercorporation',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
        migrations.AddField(
            model_name='senderperson',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='senderperson',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='senderplace',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
    ]
