# Generated by Django 5.2.4 on 2026-05-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('edwoca', '0007_rename_edition_receiver_corporation_letter_receiver_corporations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivercorporation',
            name='edition_corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.corporation'),
        ),
        migrations.AlterField(
            model_name='receiverperson',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='receiverplace',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.place'),
        ),
        migrations.AlterField(
            model_name='sendercorporation',
            name='edition_corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.corporation'),
        ),
        migrations.AlterField(
            model_name='senderperson',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='senderplace',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmad.place'),
        ),
    ]
