# Generated by Django 5.2.4 on 2026-01-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0006_alter_period_assumed_alter_period_inferred'),
        ('edwoca', '0007_merge_20260116_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodification',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification', to='dmad.period'),
        ),
    ]
