# Generated by Django 5.2.4 on 2026-10-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0012_alter_annotation_collection_component_and_more'),
        ('edwoca', '0007_alter_itemmodification_collection_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodification',
            name='collection_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='dmrism.relatedexpression'),
        ),
    ]
