# Generated by Django 5.2.4 on 2026-05-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0008_alter_receivercorporation_edition_corporation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivercorporation',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='receivercorporation',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='receivercorporation',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='receiverperson',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='receiverperson',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='receiverperson',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='receiverplace',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='receiverplace',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='receiverplace',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='sendercorporation',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='sendercorporation',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='sendercorporation',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='senderperson',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='senderperson',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='senderperson',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='senderplace',
            name='edition_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
        migrations.AlterField(
            model_name='senderplace',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relations', to='edwoca.letter'),
        ),
        migrations.AlterField(
            model_name='senderplace',
            name='source_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edwoca.documentedentityname'),
        ),
    ]
