# Generated by Django 5.1.4 on 2025-06-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0008_item_rism_id_alter_manifestation_manifestation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='history',
            new_name='location',
        ),
    ]
