# Generated by Django 5.2.4 on 2026-01-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0006_alter_period_assumed_alter_period_inferred'),
        ('edwoca', '0008_alter_itemmodification_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressioncorporationdedication',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period'),
        ),
        migrations.AlterField(
            model_name='expressionpersondedication',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period'),
        ),
        migrations.AlterField(
            model_name='workcorporationdedication',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period'),
        ),
        migrations.AlterField(
            model_name='workpersondedication',
            name='period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period'),
        ),
    ]
