# Generated by Django 5.2.4 on 2026-05-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0009_alter_receivercorporation_edition_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivercorporation',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receivercorporation',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='receivercorporation',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receivercorporation',
            name='source_name_inferred',
        ),
        migrations.RemoveField(
            model_name='receiverperson',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receiverperson',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='receiverperson',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receiverperson',
            name='source_name_inferred',
        ),
        migrations.RemoveField(
            model_name='receiverplace',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receiverplace',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='receiverplace',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='receiverplace',
            name='source_name_inferred',
        ),
        migrations.RemoveField(
            model_name='sendercorporation',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='sendercorporation',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='sendercorporation',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='sendercorporation',
            name='source_name_inferred',
        ),
        migrations.RemoveField(
            model_name='senderperson',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='senderperson',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='senderperson',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='senderperson',
            name='source_name_inferred',
        ),
        migrations.RemoveField(
            model_name='senderplace',
            name='edition_name_assumed',
        ),
        migrations.RemoveField(
            model_name='senderplace',
            name='edition_name_inferred',
        ),
        migrations.RemoveField(
            model_name='senderplace',
            name='source_name_assumed',
        ),
        migrations.RemoveField(
            model_name='senderplace',
            name='source_name_inferred',
        ),
    ]
