# Generated by Django 5.1.4 on 2025-06-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_alter_personname_status_alter_placename_status'),
        ('edwoca', '0009_rename_history_item_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwoca.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
            ],
        ),
    ]
