# Generated by Django 5.1.4 on 2025-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0010_itemcontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
