# Generated by Django 5.2.4 on 2026-05-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0010_remove_receivercorporation_edition_name_assumed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivercorporation',
            old_name='edition_corporation',
            new_name='corporation',
        ),
        migrations.RenameField(
            model_name='sendercorporation',
            old_name='edition_corporation',
            new_name='corporation',
        ),
    ]
