# Generated by Django 5.1.4 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0011_item_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='comment',
            new_name='private_comment',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='comment',
            new_name='private_comment',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='comment',
            new_name='private_comment',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='comment',
        ),
        migrations.AddField(
            model_name='expression',
            name='public_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='public_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='public_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='public_comment',
            field=models.TextField(null=True),
        ),
    ]
