# Generated by Django 5.2.4 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('edwoca', '0011_rename_edition_corporation_receivercorporation_corporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
        ),
        migrations.AddField(
            model_name='letter',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
        ),
        migrations.AddField(
            model_name='letter',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AddField(
            model_name='letter',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
        migrations.AddField(
            model_name='letter',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AddField(
            model_name='letter',
            name='work_mentionings',
            field=models.TextField(blank=True, null=True, verbose_name='work mentionings'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver_corporations',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverCorporation', to='dmad.corporation', verbose_name='receiver corporation'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver_persons',
            field=models.ManyToManyField(related_name='edition_receiver_of', through='edwoca.ReceiverPerson', to='dmad.person', verbose_name='receiver person'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver_places',
            field=models.ManyToManyField(related_name='receiver_place_of', through='edwoca.ReceiverPlace', to='dmad.place', verbose_name='receiver place'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_corporations',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderCorporation', to='dmad.corporation', verbose_name='sender corporation'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_persons',
            field=models.ManyToManyField(related_name='edition_sender_of', through='edwoca.SenderPerson', to='dmad.person', verbose_name='sender person'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender_places',
            field=models.ManyToManyField(related_name='sender_place_of', through='edwoca.SenderPlace', to='dmad.place', verbose_name='sender place'),
        ),
    ]
