# Generated by Django 5.2 on 2025-07-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0019_merge_20250702_0851'),
        ('edwoca', '0012_rename_comment_expression_private_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressioncontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iiif_manifest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='manifestationcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
    ]
