# Generated by Django 5.1.4 on 2025-07-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0016_rename_subjectterm_subjecttermname_subject_term_and_more'),
        ('edwoca', '0012_rename_comment_expression_private_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestationtitle',
            options={},
        ),
        migrations.RemoveField(
            model_name='manifestationtitle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='manifestationtitle',
            name='status',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='dedicatee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedicated_manifestations', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='dedication',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='watermark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='watermark_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestationtitle',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('HT', 'Head Title')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='manifestationtitle',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_manifestation_titles', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='expressioncontributor',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.expression'),
        ),
        migrations.AlterField(
            model_name='expressioncontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iiif_manifest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcontributor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.item'),
        ),
        migrations.AlterField(
            model_name='itemcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(choices=[('SC', 'Score'), ('PA', 'Parts')], default='SC', max_length=10),
        ),
        migrations.AlterField(
            model_name='manifestationcontributor',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.manifestation'),
        ),
        migrations.AlterField(
            model_name='manifestationcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='workcontributor',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='edwoca.work'),
        ),
    ]
