# Generated by Django 5.2.4 on 2025-07-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0013_alter_manifestationtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestationbib',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='edwoca.manifestation'),
        ),
        migrations.AlterField(
            model_name='workbib',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='edwoca.work'),
        ),
    ]
