# Generated by Django 5.2.4 on 2025-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0014_alter_manifestationbib_manifestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='is_singleton',
            field=models.BooleanField(default=False),
        ),
    ]
