# Generated by Django 5.2.4 on 2025-07-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0015_manifestation_is_singleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('siglum', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='rism_id',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1)),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='edwoca.library')),
            ],
        ),
    ]
