# Generated by Django 5.2.4 on 2025-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0016_library_remove_manifestation_rism_id_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
