# Generated by Django 5.2.4 on 2025-07-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0018_alter_library_name_alter_signature_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='role',
            new_name='status',
        ),
        migrations.AddField(
            model_name='signature',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='edwoca.item'),
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('item',), name='unique_current_signature'),
        ),
    ]
