# Generated by Django 5.2.4 on 2025-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0019_rename_role_signature_status_signature_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rism_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
