# Generated by Django 5.2.4 on 2025-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0020_alter_item_rism_id_alter_signature_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='missing_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='numerus_currens',
            field=models.IntegerField(null=True),
        ),
    ]
