# Generated by Django 5.2.4 on 2025-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0021_manifestation_missing_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rism_id',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='rism_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='numerus_currens',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
