# Generated by Django 5.2.4 on 2025-07-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0013_alter_expressioncontributor_person_and_more'),
        ('edwoca', '0022_remove_item_rism_id_manifestation_rism_id_and_more'),
    ]

    operations = [
    ]
