# Generated by Django 5.2.4 on 2025-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwoca', '0023_merge_20250723_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(choices=[('SC', 'Score'), ('PA', 'Parts'), ('PC', 'Particell'), ('PR', 'Piano Reduction'), ('CS', 'Choir Score')], default='SC', max_length=10),
        ),
    ]
