# Generated by Django 5.2.4 on 2025-08-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bib', '0002_zotitem_zot_short_title'),
        ('dmad', '0025_merge_20250723_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_comment', models.TextField(null=True)),
                ('private_comment', models.TextField(null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('handwriting', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('iiif_manifest', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('siglum', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='dmrism.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_comment', models.TextField(null=True)),
                ('private_comment', models.TextField(null=True)),
                ('rism_id_unaligned', models.BooleanField(default=False)),
                ('temporary', models.BooleanField(default=False)),
                ('plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('manifestation_type', models.CharField(choices=[('MS', 'Parent')], default='MS', max_length=10)),
                ('edition_type', models.CharField(choices=[('SC', 'Score'), ('PA', 'Parts'), ('PC', 'Particell'), ('PR', 'Piano Reduction'), ('CS', 'Choir Score')], default='SC', max_length=10)),
                ('state', models.CharField(choices=[('CP', 'complete'), ('INC', 'incomplete')], default='CP', max_length=10)),
                ('history', models.TextField(blank=True, null=True)),
                ('dedication', models.TextField(blank=True, max_length=100, null=True)),
                ('watermark', models.TextField(blank=True, max_length=100, null=True)),
                ('watermark_url', models.URLField(blank=True, null=True)),
                ('is_singleton', models.BooleanField(default=False)),
                ('missing_item', models.BooleanField(default=False)),
                ('numerus_currens', models.IntegerField(null=True, unique=True)),
                ('rism_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dedicatee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedicated_manifestations', to='dmad.person')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.place')),
                ('temporary_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_copy', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='ManifestationBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='bib',
            field=models.ManyToManyField(through='dmrism.ManifestationBib', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='ManifestationContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='dmrism.manifestation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='contributors',
            field=models.ManyToManyField(through='dmrism.ManifestationContributor', to='dmad.person'),
        ),
        migrations.CreateModel(
            name='ManifestationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_type', models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('HT', 'Head Title')], default='EN', max_length=2)),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='dmrism.manifestation')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_manifestation_titles', to='dmad.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_end', to='dmad.period')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='dmrism.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.person')),
                ('start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_start', to='dmad.period')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2)),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_item_of', to='dmrism.item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_item_of', to='dmrism.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2)),
                ('source_manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_manifestation_of', to='dmrism.manifestation')),
                ('target_manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_manifestation_of', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='related_manifestations',
            field=models.ManyToManyField(through='dmrism.RelatedManifestation', to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='dmrism.item')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='dmrism.library')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('item',), name='unique_current_signature')],
            },
        ),
    ]
