# Generated by Django 5.2.4 on 2026-02-11 18:47

import django.db.models.deletion
import dmrism.models.item
import liszt_util.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bib', '0001_initial'),
        ('dmad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(db_index=True, default=0, verbose_name='Sortier-Index')),
                ('public_comment', models.TextField(blank=True, null=True, verbose_name='public comment')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('rism_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='RISM id')),
                ('private_dedication_comment', models.TextField(blank=True, null=True, verbose_name='private dedication comment')),
                ('private_provenance_comment', models.TextField(blank=True, null=True, verbose_name='private provenance comment')),
                ('public_provenance_comment', models.TextField(blank=True, null=True, verbose_name='public provenance comment')),
                ('is_template', models.BooleanField(default=False)),
                ('extent', models.TextField(blank=True, null=True, verbose_name='extent')),
                ('measure', models.TextField(blank=True, null=True, verbose_name='measure')),
                ('private_manuscript_comment', models.TextField(blank=True, null=True, verbose_name='private manuscript comment')),
                ('taken_information', models.TextField(blank=True, null=True, verbose_name='taken information')),
            ],
            options={
                'ordering': ['manifestation', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name')),
                ('siglum', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='siglum')),
            ],
        ),
        migrations.CreateModel(
            name='CorporationProvenanceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ManyToManyField(related_name='corporation_provenance_stations', to='bib.zotitem')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_stations', to='dmad.corporation')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporation_provenance_stations', to='dmad.period')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporation_provenance_stations', to='dmrism.item')),
            ],
            bases=(dmrism.models.item.ProvenanceStationRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relations', to='dmrism.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemDigitalCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.TextField(blank=True, choices=[('Dig', 'Digitized'), ('IIIF', 'IIIF Manifest'), ('Prv', 'Private')], default='Dig', max_length=20, null=True, verbose_name='link type')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_copies', to='dmrism.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemHandwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='medium')),
                ('dubious_writer', models.BooleanField(default=False, verbose_name='dubious writer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='dmrism.item')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_comment', models.TextField(blank=True, null=True, verbose_name='public comment')),
                ('private_comment', models.TextField(blank=True, null=True, verbose_name='private comment')),
                ('working_title', models.TextField(blank=True, max_length=200, null=True, verbose_name='working title')),
                ('source_title', models.TextField(blank=True, max_length=200, null=True, verbose_name='source title')),
                ('rism_id_unaligned', models.BooleanField(default=False)),
                ('temporary', models.BooleanField(default=False)),
                ('place_inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('place_assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('manifestation_form', models.CharField(blank=True, choices=[('EX', 'Excerpts'), ('SK', 'Sketches'), ('FR', 'Fragments')], default=None, max_length=10, null=True, verbose_name='manifestation form')),
                ('source_type', models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries')], default=None, max_length=5, null=True, verbose_name='source type')),
                ('print_type', models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type')),
                ('edition', models.CharField(choices=[('1', 'first edition'), ('F', 'following edition')], default='F', max_length=10, verbose_name='edition')),
                ('state', models.CharField(choices=[('CP', 'complete'), ('INC', 'incomplete')], default='CP', max_length=10, verbose_name='state')),
                ('extent', models.TextField(blank=True, null=True, verbose_name='extent')),
                ('history', models.TextField(blank=True, null=True, verbose_name='history')),
                ('language', models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default=None, max_length=15, null=True, verbose_name='language')),
                ('watermark', models.TextField(blank=True, max_length=100, null=True, verbose_name='watermark')),
                ('watermark_url', models.URLField(blank=True, null=True, verbose_name='watermark url')),
                ('is_singleton', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
                ('missing_item', models.BooleanField(default=False)),
                ('numerus_currens', models.IntegerField(null=True, unique=True)),
                ('rism_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='RISM id')),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('date_diplomatic', models.TextField(blank=True, null=True, verbose_name='diplomatic date')),
                ('print_extent', models.TextField(blank=True, null=True, verbose_name='print extent')),
                ('private_head_comment', models.TextField(blank=True, null=True, verbose_name='private head comment')),
                ('private_relations_comment', models.TextField(blank=True, null=True, verbose_name='private relations comment')),
                ('private_title_comment', models.TextField(blank=True, null=True, verbose_name='private title comment')),
                ('private_history_comment', models.TextField(blank=True, null=True, verbose_name='private history comment')),
                ('private_dedication_comment', models.TextField(blank=True, null=True, verbose_name='private dedication comment')),
                ('private_print_comment', models.TextField(blank=True, null=True, verbose_name='private print comment')),
                ('taken_information', models.TextField(blank=True, null=True, verbose_name='taken information')),
                ('specific_figure', models.BooleanField(default=False, verbose_name='specific figure')),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='plate number')),
                ('album_page', models.BooleanField(default=False, verbose_name='album page')),
                ('performance_material', models.BooleanField(default=False, verbose_name='performance material')),
                ('correction_sheet', models.BooleanField(default=False, verbose_name='correction sheet')),
                ('stitch_template', models.BooleanField(default=False, verbose_name='stitch template')),
                ('dedication_item', models.BooleanField(default=False, verbose_name='dedication item')),
                ('choir_score', models.BooleanField(default=False, verbose_name='choir score')),
                ('piano_reduction', models.BooleanField(default=False, verbose_name='piano reduction')),
                ('particell', models.BooleanField(default=False, verbose_name='particell')),
                ('score', models.BooleanField(default=False, verbose_name='score')),
                ('parts', models.BooleanField(default=False, verbose_name='parts')),
                ('first_save', models.DateTimeField(auto_now_add=True, verbose_name='first save')),
                ('last_save', models.DateTimeField(auto_now=True, verbose_name='last save')),
                ('first_editor', models.CharField(blank=True, max_length=50, null=True)),
                ('editing_history', models.TextField(blank=True, null=True)),
                ('component_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_components', to='dmrism.manifestation')),
                ('part_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_parts', to='dmrism.manifestation')),
                ('period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period')),
                ('places', models.ManyToManyField(to='dmad.place')),
                ('stitcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitched_manifestations', to='dmad.corporation')),
                ('temporary_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_copy', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
            bases=(liszt_util.tools.RenderRawJSONMixin, models.Model),
        ),
        migrations.AddField(
            model_name='item',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='ManifestationBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='bib',
            field=models.ManyToManyField(through='dmrism.ManifestationBib', to='bib.zotitem'),
        ),
        migrations.CreateModel(
            name='ManifestationCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_corporation_dedications', to='dmrism.manifestation')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManifestationPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True, verbose_name='dedication text')),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_person_dedications', to='dmrism.manifestation')),
                ('period', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManifestationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='diplomatic title')),
                ('title_type', models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('ET', 'Envelope or Title Page'), ('HT', 'Head Title')], default=None, max_length=2, null=True, verbose_name='title type')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='dmrism.manifestation')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestationTitleHandwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='medium')),
                ('dubious_writer', models.BooleanField(default=False, verbose_name='dubious writer')),
                ('manifestation_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='dmrism.manifestationtitle')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonProvenanceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.ManyToManyField(related_name='person_provenance_stations', to='bib.zotitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_provenance_stations', to='dmrism.item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_stations', to='dmad.person')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_provenance_stations', to='dmad.period')),
            ],
            bases=(dmrism.models.item.ProvenanceStationRenderMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='dmrism.manifestation')),
                ('place', models.ManyToManyField(related_name='published_manifestations', to='dmad.place')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_manifestations', to='dmad.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('label', models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2, verbose_name='label')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_item_of', to='dmrism.item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_item_of', to='dmrism.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('label', models.CharField(choices=[('A', 'has alternative')], max_length=1, null=True, verbose_name='label')),
                ('order', models.IntegerField(default=0)),
                ('source_manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_manifestation_of', to='dmrism.manifestation')),
                ('target_manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_manifestation_of', to='dmrism.manifestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='related_manifestations',
            field=models.ManyToManyField(through='dmrism.RelatedManifestation', to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='ItemSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=20, null=True, verbose_name='signature')),
                ('status', models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1, verbose_name='status')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='dmrism.item')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library', verbose_name='holding institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('item',), name='unique_current_item_signature')],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True)), fields=('manifestation',), name='unique_template_item_per_manifestation'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('manifestation', 'order_index')},
        ),
    ]
