# Generated by Django 5.2.4 on 2025-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rism_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
