# Generated by Django 5.2.4 on 2025-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signature',
            name='unique_current_signature',
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('item',), name='unique_current_item_signature'),
        ),
    ]
