# Generated by Django 5.2.4 on 2026-03-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='parts',
        ),
    ]
