# Generated by Django 5.2.4 on 2025-08-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_type', models.TextField(blank=True, max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_copies', to='dmrism.item')),
            ],
        ),
    ]
