# Generated by Django 5.2.4 on 2026-03-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='authorized_edition',
            field=models.BooleanField(default=False, verbose_name='authorized edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='first_edition',
            field=models.BooleanField(default=False, verbose_name='first edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='further_edition',
            field=models.BooleanField(default=False, verbose_name='further edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='part',
            field=models.BooleanField(default=False, verbose_name='part'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='proof',
            field=models.BooleanField(default=False, verbose_name='proof'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='editing_history',
            field=models.TextField(blank=True, null=True, verbose_name='editing history'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='edition',
            field=models.CharField(choices=[('1', 'first issue'), ('F', 'following issue')], default='F', max_length=10, verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='first_editor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first editor'),
        ),
    ]
