# Generated by Django 5.2.4 on 2025-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='extent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='measure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
