# Generated by Django 5.2.4 on 2026-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcorporationdedication',
            name='dedicatee',
        ),
        migrations.RemoveField(
            model_name='itempersondedication',
            name='dedicatee',
        ),
        migrations.RemoveField(
            model_name='manifestationcorporationdedication',
            name='dedicatee',
        ),
        migrations.RemoveField(
            model_name='manifestationpersondedication',
            name='dedicatee',
        ),
        migrations.AddField(
            model_name='itemcorporationdedication',
            name='dedicatee',
            field=models.ManyToManyField(related_name='%(class)s', to='dmad.corporation'),
        ),
        migrations.AddField(
            model_name='itempersondedication',
            name='dedicatee',
            field=models.ManyToManyField(related_name='%(class)s', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='manifestationcorporationdedication',
            name='dedicatee',
            field=models.ManyToManyField(related_name='%(class)s', to='dmad.corporation'),
        ),
        migrations.AddField(
            model_name='manifestationpersondedication',
            name='dedicatee',
            field=models.ManyToManyField(related_name='%(class)s', to='dmad.person'),
        ),
    ]
