# Generated by Django 5.2.4 on 2025-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifestation',
            old_name='raw_marc',
            new_name='raw_data',
        ),
    ]
