# Generated by Django 5.2.4 on 2026-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='edition',
            field=models.CharField(choices=[('1', 'first edition'), ('F', 'following edition')], default='F', max_length=10, verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='extent',
            field=models.TextField(blank=True, null=True, verbose_name='extent'),
        ),
    ]
