# Generated by Django 5.2.4 on 2025-09-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='publisher',
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.manifestation')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_manifestations', to='dmad.corporation')),
            ],
        ),
    ]
