# Generated by Django 5.2.4 on 2025-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='public_provenance_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
