# Generated by Django 5.2.4 on 2025-09-10 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_stations', to='dmad.corporation'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_stations', to='dmad.person'),
        ),
    ]
