# Generated by Django 5.2.4 on 2026-04-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestation',
            options={'ordering': ['-needs_review']},
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_explanation',
            field=models.BooleanField(default=False, verbose_name='is explanation'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_lyrics',
            field=models.BooleanField(default=False, verbose_name='is lyrics'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_program',
            field=models.BooleanField(default=False, verbose_name='is program'),
        ),
        migrations.AlterField(
            model_name='itemsignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='signature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='date_diplomatic',
            field=models.TextField(blank=True, default='', verbose_name='diplomatic date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='extent',
            field=models.TextField(blank=True, default='', verbose_name='extent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='history',
            field=models.TextField(blank=True, default='', verbose_name='history'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='plate number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_extent',
            field=models.TextField(blank=True, default='', verbose_name='print extent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_dedication_comment',
            field=models.TextField(blank=True, default='', verbose_name='private dedication comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_head_comment',
            field=models.TextField(blank=True, default='', verbose_name='private head comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_history_comment',
            field=models.TextField(blank=True, default='', verbose_name='private history comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_print_comment',
            field=models.TextField(blank=True, default='', verbose_name='private print comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_relations_comment',
            field=models.TextField(blank=True, default='', verbose_name='private relations comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_title_comment',
            field=models.TextField(blank=True, default='', verbose_name='private title comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='raw_data',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='rism_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RISM id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_title',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='source title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries')], default='AUT', max_length=5, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='taken_information',
            field=models.TextField(blank=True, default='', verbose_name='taken information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='temporary_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_copy', to='dmrism.manifestation'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='watermark',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='watermark'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='watermark_url',
            field=models.URLField(blank=True, default='', verbose_name='watermark url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='working_title',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='working title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(blank=True, choices=[('HT', 'Head Title'), ('TP', 'Title Page'), ('EN', 'Envelope'), ('ET', 'Envelope or Title Page')], default=None, max_length=2, null=True, verbose_name='title type'),
        ),
    ]
