# Generated by Django 5.2.4 on 2026-04-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_manifestation_options_item_is_explanation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['siglum', 'name']},
        ),
        migrations.AddField(
            model_name='manifestation',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='sorting index'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='sorting index'),
        ),
    ]
