# Generated by Django 5.2.4 on 2025-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_item_rism_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['manifestation', 'order_index']},
        ),
        migrations.AddField(
            model_name='item',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortier-Index'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('manifestation', 'order_index')},
        ),
    ]
