# Generated by Django 5.2.4 on 2026-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_library_options_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('SK', 'Sketches')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
