# Generated by Django 5.2.4 on 2026-06-17 14:58

import django.db.migrations.operations.special
from django.db import migrations, models

def update_ownership(apps, schema_editor):
    Pps = apps.get_model('dmrism', 'PersonProvenanceStation')
    Cps = apps.get_model('dmrism', 'CorporationProvenanceStation')

    Pps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Cps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Pps.objects.filter(period_status = 'per').update(period_status = 'own')
    Cps.objects.filter(period_status = 'per').update(period_status = 'own')

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dmrism.migrations.0004_join_ownership

class Migration(migrations.Migration):

    replaces = [('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more'), ('dmrism', '0004_join_ownership'), ('dmrism', '0005_alter_corporationprovenancestation_period_status_and_more')]

    dependencies = [
        ('dmrism', '0002_alter_library_options_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.RunPython(
            code=update_ownership,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
    ]
