# Generated by Django 5.2.4 on 2025-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0002_alter_corporationprovenancestation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dedicatees',
            field=models.ManyToManyField(related_name='item_dedicatees', to='dmad.person'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalcopy',
            name='link_type',
            field=models.TextField(blank=True, choices=[('Dig', 'Digitized'), ('IIIF', 'IIIF Manifest')], default='Dig', max_length=20, null=True),
        ),
    ]
