# Generated by Django 5.2.4 on 2025-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_remove_signature_unique_current_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='manifestation_type',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(choices=[('SK', 'Sketch'), ('FR', 'Fragment'), ('EX', 'Excerpts')], default='SK', max_length=10),
        ),
    ]
