# Generated by Django 5.2.4 on 2026-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_explanation',
            field=models.BooleanField(default=False, verbose_name='is explanation'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_lyrics',
            field=models.BooleanField(default=False, verbose_name='is lyrics'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_program',
            field=models.BooleanField(default=False, verbose_name='is program'),
        ),
    ]
