# Generated by Django 5.2.4 on 2026-01-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0001_initial'),
        ('dmrism', '0002_manifestation_edition_manifestation_extent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='place',
        ),
        migrations.AddField(
            model_name='publication',
            name='place',
            field=models.ManyToManyField(related_name='published_manifestations', to='dmad.place'),
        ),
    ]
