# Generated by Django 5.2.4 on 2025-09-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0002_remove_manifestation_plate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dedicatees',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dedication',
        ),
        migrations.RemoveField(
            model_name='item',
            name='handwriting',
        ),
        migrations.RemoveField(
            model_name='item',
            name='iiif_manifest',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='handwriting',
        ),
        migrations.AlterField(
            model_name='publication',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='dmrism.manifestation'),
        ),
        migrations.CreateModel(
            name='ItemCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManifestationCorporationDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_corporation_dedications', to='dmrism.manifestation')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManifestationPersonDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomatic_dedication', models.TextField(blank=True, null=True)),
                ('dedicatee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.person')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_person_dedications', to='dmrism.manifestation')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.period')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
