# Generated by Django 5.2.4 on 2026-03-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_manifestation_needs_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationProvenanceStationWebReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='web reference comment')),
                ('corporation_provenance_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_references', to='dmrism.corporationprovenancestation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonProvenanceStationWebReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='web reference comment')),
                ('person_provenance_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_references', to='dmrism.personprovenancestation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
