# Generated by Django 5.2.4 on 2026-07-14 08:46

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models

def update_ownership(apps, schema_editor):
    Pps = apps.get_model('dmrism', 'PersonProvenanceStation')
    Cps = apps.get_model('dmrism', 'CorporationProvenanceStation')

    Pps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Cps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Pps.objects.filter(period_status = 'per').update(period_status = 'own')
    Cps.objects.filter(period_status = 'per').update(period_status = 'own')

def migrate_completeness(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    for m in Manifestation.objects.filter(is_singleton = True, completeness = 'i'):
        i = m.items.first()
        i.is_incomplete = True
        i.save()

def migrate_text_types(apps, schema_editor):
    Item = apps.get_model('edwoca', 'item')

    for i in Item.objects.filter(manifestation__is_singleton=True):
        for prop in ['is_lyrics', 'is_program', 'is_explanation']:
            if getattr(i, prop):
                setattr(i.manifestation, prop, True)
                setattr(i, prop, False)
        i.manifestation.save()

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dmrism.migrations.0003_alter_corporationprovenancestation_period_status_and_more_squashed

class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
        ('dmad', '0003_period_end_qualifier_period_start_qualifier_and_more_squashed'),
        ('dmrism', '0002_alter_library_options_alter_manifestation_options_and_more'),
        ('edwoca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.RunPython(
            code=update_ownership,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.RunPython(
            code=migrate_completeness,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='completeness',
        ),
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='corporationprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='personprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='assumed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='inferred',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='edition_by_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='edition by source'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_partial_edition',
            field=models.BooleanField(default=False, verbose_name='partial edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.CreateModel(
            name='PublicationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='dmad.place')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_relations', to='dmrism.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='is_incomplete',
        ),
        migrations.AddField(
            model_name='publication',
            name='places',
            field=models.ManyToManyField(related_name='published_manifestations', through='dmrism.PublicationPlace', to='dmad.place'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='place',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_explanation',
            field=models.BooleanField(default=False, verbose_name='is explanation'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_lyrics',
            field=models.BooleanField(default=False, verbose_name='is lyrics'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_program',
            field=models.BooleanField(default=False, verbose_name='is program'),
        ),
        migrations.RunPython(
            code=migrate_text_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-needs_review', 'manifestation', 'order_index']},
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='proof',
        ),
        migrations.AddField(
            model_name='item',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
        migrations.AddField(
            model_name='item',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('SK', 'Sketches'), ('PR', 'proof')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_title',
            field=models.TextField(blank=True, default='', verbose_name='source title'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries'), ('PRT', 'print')], default='AUT', max_length=5, null=True, verbose_name='source type'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='title_page',
            field=models.TextField(blank=True, default='', verbose_name='title page diplomatic'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='working_title',
            field=models.TextField(blank=True, default='', verbose_name='working title'),
        ),
        migrations.CreateModel(
            name='ItemBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='bib location')),
                ('location_type', models.CharField(choices=[('P', 'page'), ('C', 'column'), ('L', 'lot')], default='P', max_length=1, verbose_name='bib location type')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='dmrism.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
