# Generated by Django 5.2.4 on 2025-11-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_manifestation_extent_manifestation_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='extent',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='measure',
        ),
        migrations.AddField(
            model_name='item',
            name='taken_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
