# Generated by Django 5.2.4 on 2026-04-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_manifestation_options_item_is_explanation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['siglum', 'name']},
        ),
    ]
