# Generated by Django 5.2.4 on 2025-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_digitalcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedmanifestation',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('ET', 'Envelope or Title Page'), ('HT', 'Head Title')], default=None, max_length=2, null=True),
        ),
    ]
