# Generated by Django 5.2.4 on 2026-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_library_options_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries')], default='AUT', max_length=5, null=True, verbose_name='source type'),
        ),
    ]
