# Generated by Django 5.2.4 on 2026-06-24 06:37

import django.db.migrations.operations.special
from django.db import migrations, models


def migrate_completeness(apps, schema_editor):
    Manifestation = apps.get_model('edwoca', 'manifestation')

    Manifestation.objects.filter(manifestation_form = 'EX').update(completeness = 'i')

    for m in Manifestation.objects.filter(manifestation_form = 'FR'):
        m.private_comment = m.private_comment + '\nFragment'
        m.needs_review = True
        m.save()

    Manifestation.objects.filter(manifestation_form = 'EX').update(manifestation_form = None)
    Manifestation.objects.filter(manifestation_form = 'FR').update(manifestation_form = None)


def update_ownership(apps, schema_editor):
    Pps = apps.get_model('dmrism', 'PersonProvenanceStation')
    Cps = apps.get_model('dmrism', 'CorporationProvenanceStation')

    Pps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Cps.objects.filter(period_status = 'dat').update(period_status = 'own')
    Pps.objects.filter(period_status = 'per').update(period_status = 'own')
    Cps.objects.filter(period_status = 'per').update(period_status = 'own')

def transfer_completeness(apps, schema_editor):
    manifestations = apps.get_model('dmrism', 'manifestation').objects.all()

    for manifestation in manifestations:
        if manifestation.completeness == 'c':
            manifestation.is_incomplete = False
        else:
            manifestation.is_incomplete = True

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dmrism.migrations.0003_alter_corporationprovenancestation_period_status_and_more
# dmrism.migrations.0005_transfer_completeness

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_alter_library_options_alter_manifestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date'), ('own', 'ownership')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.RunPython(
            code=update_ownership,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, verbose_name='period status'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.RunPython(migrate_completeness, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            code=transfer_completeness,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='completeness',
        ),
    ]
