# Generated by Django 5.2.4 on 2025-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0002_rename_raw_marc_manifestation_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='extent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='handwriting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='paper',
            field=models.TextField(blank=True, null=True),
        ),
    ]
