# Generated by Django 5.2.4 on 2026-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
    ]
