# Generated by Django 5.2.4 on 2025-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_manifestation_extent_manifestation_handwriting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(choices=[('SCO', 'Score'), ('PRT', 'Part'), ('PTS', 'Parts'), ('PTC', 'Particell'), ('PNR', 'Piano Reduction'), ('CSC', 'Choir Score')], default=None, max_length=10, null=True),
        ),
    ]
