# Generated by Django 5.2.4 on 2025-09-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0003_relatedmanifestation_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='manifestationtitle',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='manifestationtitle',
            name='writer',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='dedicatees',
            field=models.ManyToManyField(to='dmad.person'),
        ),
        migrations.AlterField(
            model_name='manifestationhandwriting',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='dmrism.manifestation'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestationtitlehandwriting',
            name='manifestation_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='dmrism.manifestationtitle'),
        ),
        migrations.DeleteModel(
            name='ManifestationContributor',
        ),
    ]
