# Generated by Django 5.2.4 on 2026-04-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_library_options_manifestation_order_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestation',
            options={'ordering': ['-needs_review', 'order_index']},
        ),
    ]
