# Generated by Django 5.2.4 on 2026-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_manifestation_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='is_explanation',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='is_lyrics',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='is_program',
        ),
        migrations.AlterField(
            model_name='itemsignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='signature'),
        ),
    ]
