# Generated by Django 5.2.4 on 2026-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_remove_publication_place_publication_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='place_status',
        ),
        migrations.AddField(
            model_name='publication',
            name='assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='publication',
            name='inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
    ]
