# Generated by Django 5.2.4 on 2025-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_item_dedicatees_item_dedication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='private_provenance_comment',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='public_provenance_comment',
        ),
        migrations.AddField(
            model_name='item',
            name='private_provenance_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='public_provenance_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
