# Generated by Django 5.2.4 on 2025-11-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_remove_manifestation_extent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='print_extent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
