# Generated by Django 5.2.4 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_item_is_explanation_item_is_lyrics_item_is_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='is_text',
            field=models.BooleanField(default=False, verbose_name='is text'),
        ),
    ]
