# Generated by Django 5.2.4 on 2026-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_corporationprovenancestationwebreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date')], default='per', max_length=3),
        ),
        migrations.AddField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date')], default='per', max_length=3),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries')], default='AUT', max_length=5, null=True, verbose_name='source type'),
        ),
    ]
