# Generated by Django 5.2.4 on 2026-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source_type',
            field=models.CharField(blank=True, choices=[('PRC', 'proof copy'), ('APC', 'annotated proof copy'), ('MPR', 'modified print')], default=None, max_length=3, null=True, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('MPR', 'modified print'), ('PRT', 'print')], default='AUT', max_length=5, null=True, verbose_name='source type'),
        ),
    ]
