# Generated by Django 5.2.4 on 2026-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
    ]
