# Generated by Django 5.2.4 on 2026-07-09 08:50

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models

def migrate_completeness(apps, schema_editor):
    Manifestation = apps.get_model('edwoca', 'manifestation')

    for m in Manifestation.objects.filter(is_singleton = True, is_incomplete = True):
        i = m.get_single_item()
        i.is_incomplete = True
        i.save()

def migrate_text_types(apps, schema_editor):
    Item = apps.get_model('edwoca', 'item')

    for i in Item.objects.filter(manifestation__is_singleton=True):
        for prop in ['is_lyrics', 'is_program', 'is_explanation']:
            if getattr(i, prop):
                setattr(i.manifestation, prop, True)
                setattr(i, prop, False)
        i.manifestation.save()

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dmrism.migrations.0007_migrate_completeness
# dmrism.migrations.0013_migrate_text_types

class Migration(migrations.Migration):

    replaces = [('dmrism', '0004_alter_corporationprovenancestation_period_status_and_more'), ('dmrism', '0005_alter_corporationprovenancestationwebreference_url_and_more'), ('dmrism', '0006_remove_publication_assumed_and_more'), ('dmrism', '0007_migrate_completeness'), ('dmrism', '0008_remove_manifestation_is_incomplete'), ('dmrism', '0009_publication_places_alter_publication_place'), ('dmrism', '0011_remove_publication_place'), ('dmrism', '0012_manifestation_is_explanation_manifestation_is_lyrics_and_more'), ('dmrism', '0013_migrate_text_types'), ('dmrism', '0014_manifestation_title_page'), ('dmrism', '0015_alter_item_options_remove_manifestation_proof_and_more')]

    dependencies = [
        ('dmad', '0005_alter_period_time_mode'),
        ('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(blank=True, choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('own', 'ownership')], default='own', max_length=3, null=True, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='corporationprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='personprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='assumed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='inferred',
        ),
        migrations.AddField(
            model_name='item',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='edition_by_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='edition by source'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_partial_edition',
            field=models.BooleanField(default=False, verbose_name='partial edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.CreateModel(
            name='PublicationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='dmad.place')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_relations', to='dmrism.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=migrate_completeness,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='is_incomplete',
        ),
        migrations.AddField(
            model_name='publication',
            name='places',
            field=models.ManyToManyField(related_name='published_manifestations', through='dmrism.PublicationPlace', to='dmad.place'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='place',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_explanation',
            field=models.BooleanField(default=False, verbose_name='is explanation'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_lyrics',
            field=models.BooleanField(default=False, verbose_name='is lyrics'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_program',
            field=models.BooleanField(default=False, verbose_name='is program'),
        ),
        migrations.RunPython(
            code=migrate_text_types,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='manifestation',
            name='title_page',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='title page diplomatic'),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-needs_review', 'manifestation', 'order_index']},
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='proof',
        ),
        migrations.AddField(
            model_name='item',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
        migrations.AddField(
            model_name='item',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('SK', 'Sketches'), ('PR', 'proof')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
