# Generated by Django 5.2.4 on 2026-06-22 08:37

from django.db import migrations

def transfer_completeness(apps, schema_editor):
    manifestations = apps.get_model('dmrism', 'manifestation').objects.all()

    for manifestation in manifestations:
        if manifestation.completeness == 'c':
            manifestation.is_incomplete = False
        else:
            manifestation.is_incomplete = True

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_manifestation_is_incomplete_and_more'),
    ]

    operations = [
            migrations.RunPython(
                    transfer_completeness,
                    reverse_code=migrations.RunPython.noop
                )
        ]
