# Generated by Django 5.2.4 on 2025-12-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_manifestation_print_extent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extent',
            field=models.TextField(blank=True, null=True, verbose_name='extent'),
        ),
        migrations.AlterField(
            model_name='item',
            name='measure',
            field=models.TextField(blank=True, null=True, verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='item',
            name='private_comment',
            field=models.TextField(null=True, verbose_name='private comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='private_dedication_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private dedication comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='private_manuscript_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private manuscript comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='private_provenance_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private provenance comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='public_comment',
            field=models.TextField(null=True, verbose_name='public comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='public_provenance_comment',
            field=models.TextField(blank=True, null=True, verbose_name='public provenance comment'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rism_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RISM id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='taken_information',
            field=models.TextField(blank=True, null=True, verbose_name='taken information'),
        ),
        migrations.AlterField(
            model_name='itemcontributor',
            name='role',
            field=models.CharField(choices=[('CP', 'Composer'), ('WR', 'Writer'), ('TR', 'Translator'), ('PT', 'Poet'), ('DD', 'Dedicatee')], default='CP', max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='itemcorporationdedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='itemdigitalcopy',
            name='link_type',
            field=models.TextField(blank=True, choices=[('Dig', 'Digitized'), ('IIIF', 'IIIF Manifest'), ('Prv', 'Private')], default='Dig', max_length=20, null=True, verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='itemdigitalcopy',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='itemhandwriting',
            name='dubious_writer',
            field=models.BooleanField(default=False, verbose_name='dubious writer'),
        ),
        migrations.AlterField(
            model_name='itemhandwriting',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='itempersondedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='itemsignature',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library'),
        ),
        migrations.AlterField(
            model_name='itemsignature',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='itemsignature',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('F', 'Former')], default='C', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='library',
            name='siglum',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='siglum'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='date_diplomatic',
            field=models.TextField(blank=True, null=True, verbose_name='diplomatic date'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(blank=True, choices=[('SCO', 'Score'), ('PRT', 'Part'), ('PTS', 'Parts'), ('PTC', 'Particell'), ('PNR', 'Piano Reduction'), ('CSC', 'Choir Score')], default=None, max_length=10, null=True, verbose_name='edition type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='function',
            field=models.CharField(blank=True, choices=[('COP', 'Copy'), ('ABP', 'Album Page'), ('PTE', 'Part Excerpt'), ('DDI', 'Dedication Item'), ('STT', 'Stitch Template'), ('CST', 'Corrected Stitch Template'), ('CRS', 'Correction Sheet')], default=None, max_length=5, null=True, verbose_name='function'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('FR', 'French'), ('HU', 'Hungarian'), ('EN', 'English'), ('AA', 'Afar'), ('AB', 'Abkhazian; Abkhaz'), ('', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'), ('AF', 'Afrikaans'), ('AK', 'Akan'), ('SQ', 'Albanian'), ('AM', 'Amharic'), ('AR', 'Arabic'), ('AN', 'Aragonese'), ('HY', 'Armenian'), ('AS', 'Assamese'), ('AV', 'Avaric'), ('AE', 'Avestan'), ('AY', 'Aymara'), ('AZ', 'Azerbaijani'), ('BA', 'Bashkir'), ('BM', 'Bambara'), ('EU', 'Basque'), ('BE', 'Belarusian'), ('BN', 'Bengali; Bangla'), ('BH', 'Bihari languages; Bihari'), ('BI', 'Bislama'), ('BS', 'Bosnian'), ('BR', 'Breton'), ('BG', 'Bulgarian'), ('MY', 'Burmese'), ('CA', 'Catalan; Valencian'), ('CH', 'Chamorro'), ('CE', 'Chechen'), ('ZH', 'Chinese'), ('CU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'), ('CV', 'Chuvash'), ('KW', 'Cornish'), ('CO', 'Corsican'), ('CR', 'Cree'), ('CS', 'Czech'), ('DA', 'Danish'), ('DV', 'Divehi; Dhivehi; Maldivian'), ('NL', 'Dutch; Flemish'), ('DZ', 'Dzongkha'), ('EO', 'Esperanto'), ('ET', 'Estonian'), ('EE', 'Ewe'), ('FO', 'Faroese'), ('FJ', 'Fijian'), ('FI', 'Finnish'), ('FY', 'Western Frisian'), ('FF', 'Fulah; Fula; Pulaar; Pular'), ('KA', 'Georgian'), ('GD', 'Gaelic; Scottish Gaelic'), ('GA', 'Irish'), ('GL', 'Galician'), ('GV', 'Manx'), ('EL', 'Greek, Modern (1453-); Greek'), ('GN', 'Guarani; Guaraní'), ('GU', 'Gujarati'), ('HT', 'Haitian; Haitian Creole'), ('HA', 'Hausa'), ('HE', 'Hebrew'), ('HZ', 'Herero'), ('HI', 'Hindi'), ('HO', 'Hiri Motu'), ('HR', 'Croatian'), ('IG', 'Igbo'), ('IS', 'Icelandic'), ('IO', 'Ido'), ('II', 'Sichuan Yi; Nuosu'), ('IU', 'Inuktitut'), ('IE', 'Interlingue; Occidental'), ('IA', 'Interlingua (International Auxiliary Language Association)'), ('ID', 'Indonesian'), ('IK', 'Inupiaq'), ('IT', 'Italian'), ('JV', 'Javanese'), ('JA', 'Japanese'), ('KL', 'Kalaallisut; Greenlandic'), ('KN', 'Kannada'), ('KS', 'Kashmiri'), ('KR', 'Kanuri'), ('KK', 'Kazakh'), ('KM', 'Central Khmer; Khmer'), ('KI', 'Kikuyu; Gikuyu'), ('RW', 'Kinyarwanda'), ('KY', 'Kirghiz; Kyrgyz'), ('KV', 'Komi'), ('KG', 'Kongo'), ('KO', 'Korean'), ('KJ', 'Kuanyama; Kwanyama'), ('KU', 'Kurdish'), ('LO', 'Lao'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LI', 'Limburgan; Limburger; Limburgish'), ('LN', 'Lingala'), ('LT', 'Lithuanian'), ('LB', 'Luxembourgish; Letzeburgesch'), ('LU', 'Luba-Katanga'), ('LG', 'Ganda'), ('MK', 'Macedonian'), ('MH', 'Marshallese'), ('ML', 'Malayalam'), ('MI', 'Maori; Māori'), ('MR', 'Marathi; Marāṭhī'), ('MS', 'Malay'), ('MG', 'Malagasy'), ('MT', 'Maltese'), ('MN', 'Mongolian'), ('NA', 'Nauru; Nauruan'), ('NV', 'Navajo; Navaho'), ('NR', 'Ndebele, South; South Ndebele; Southern Ndebele'), ('ND', 'Ndebele, North; North Ndebele; Northern Ndebele'), ('NG', 'Ndonga'), ('NE', 'Nepali'), ('NN', 'Norwegian Nynorsk; Nynorsk, Norwegian'), ('NB', 'Bokmål, Norwegian; Norwegian Bokmål'), ('NO', 'Norwegian'), ('NY', 'Chichewa; Chewa; Nyanja'), ('OC', 'Occitan (post 1500); Provençal'), ('OJ', 'Ojibwa; Ojibwe'), ('OR', 'Oriya'), ('OM', 'Oromo'), ('OS', 'Ossetian; Ossetic'), ('PA', 'Panjabi; Punjabi'), ('FA', 'Persian; Farsi'), ('PI', 'Pali; Pāli'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PS', 'Pushto; Pashto'), ('QU', 'Quechua'), ('RC', 'Reunionese;Reunion Creole'), ('RM', 'Romansh'), ('RO', 'Romanian; Moldavian; Moldovan'), ('RN', 'Rundi; Kirundi'), ('RU', 'Russian'), ('SG', 'Sango'), ('SA', 'Sanskrit; Saṁskṛta'), ('SI', 'Sinhala; Sinhalese'), ('SK', 'Slovak'), ('SL', 'Slovenian; Slovene'), ('SE', 'Northern Sami'), ('SM', 'Samoan'), ('SN', 'Shona'), ('SD', 'Sindhi'), ('SO', 'Somali'), ('ST', 'Sotho, Southern; Southern Sotho'), ('ES', 'Spanish; Castilian'), ('SC', 'Sardinian'), ('SR', 'Serbian'), ('SS', 'Swati'), ('SU', 'Sundanese'), ('SW', 'Swahili'), ('SV', 'Swedish'), ('TY', 'Tahitian'), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TG', 'Tajik'), ('TL', 'Tagalog'), ('TH', 'Thai'), ('BO', 'Tibetan; Tibetan Standard; Central'), ('TI', 'Tigrinya'), ('TO', 'Tonga (Tonga Islands)'), ('TN', 'Tswana'), ('TS', 'Tsonga'), ('TK', 'Turkmen'), ('TR', 'Turkish'), ('TW', 'Twi'), ('UG', 'Uighur; Uyghur'), ('UK', 'Ukrainian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VE', 'Venda'), ('VI', 'Vietnamese'), ('VO', 'Volapük'), ('CY', 'Welsh'), ('WA', 'Walloon'), ('WO', 'Wolof'), ('XH', 'Xhosa'), ('YI', 'Yiddish'), ('YO', 'Yoruba'), ('ZA', 'Zhuang; Chuang'), ('ZU', 'Zulu')], default=None, max_length=15, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('SK', 'Sketches'), ('FR', 'Fragments'), ('EX', 'Excerpts')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_extent',
            field=models.TextField(blank=True, null=True, verbose_name='print extent'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_comment',
            field=models.TextField(null=True, verbose_name='private comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_head_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private head comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_history_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private history comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_print_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private print comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_relations_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private relations comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='private_title_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private title comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='public_comment',
            field=models.TextField(null=True, verbose_name='public comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='rism_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RISM id'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('AUT', 'Autograph'), ('CPY', 'Abschrift'), ('CCP', 'Korrigierte Abschrift'), ('PRT', 'Print'), ('CPR', 'Corrected Print')], default=None, max_length=5, null=True, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='specific_figure',
            field=models.BooleanField(default=False, verbose_name='specific figure'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='state',
            field=models.CharField(choices=[('CP', 'complete'), ('INC', 'incomplete')], default='CP', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='taken_information',
            field=models.TextField(blank=True, null=True, verbose_name='taken information'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='watermark',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='watermark'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='watermark_url',
            field=models.URLField(blank=True, null=True, verbose_name='watermark url'),
        ),
        migrations.AlterField(
            model_name='manifestationcorporationdedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='manifestationpersondedication',
            name='diplomatic_dedication',
            field=models.TextField(blank=True, null=True, verbose_name='dedication text'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('ET', 'Envelope or Title Page'), ('HT', 'Head Title')], default=None, max_length=2, null=True, verbose_name='title type'),
        ),
        migrations.AlterField(
            model_name='manifestationtitlehandwriting',
            name='dubious_writer',
            field=models.BooleanField(default=False, verbose_name='dubious writer'),
        ),
        migrations.AlterField(
            model_name='manifestationtitlehandwriting',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='plate number'),
        ),
        migrations.AlterField(
            model_name='relateditem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='relateditem',
            name='label',
            field=models.CharField(choices=[('PR', 'Parent'), ('RE', 'Related')], default='PR', max_length=2, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('PA', 'Parent'), ('RE', 'Related')], default='PA', max_length=10, verbose_name='label'),
        ),
    ]
