# Generated by Django 5.2.4 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_alter_manifestation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsignature',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='signature'),
        ),
    ]
