# Generated by Django 5.2.4 on 2025-08-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_alter_manifestation_edition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestationtitle',
            name='status',
            field=models.CharField(choices=[('P', 'Primary'), ('A', 'Alternative'), ('T', 'Temporary')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(choices=[('EN', 'Envelope'), ('TP', 'Title Page'), ('HT', 'Head Title')], default=None, max_length=2, null=True),
        ),
    ]
