# Generated by Django 5.2.4 on 2026-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_remove_publication_place_status_publication_assumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='album_page',
            field=models.BooleanField(default=False, verbose_name='album page'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='choir_score',
            field=models.BooleanField(default=False, verbose_name='choir score'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='correction_sheet',
            field=models.BooleanField(default=False, verbose_name='correction sheet'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='dedication_item',
            field=models.BooleanField(default=False, verbose_name='dedication item'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='particell',
            field=models.BooleanField(default=False, verbose_name='particell'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='parts',
            field=models.BooleanField(default=False, verbose_name='parts'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='performance_material',
            field=models.BooleanField(default=False, verbose_name='performance material'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='piano_reduction',
            field=models.BooleanField(default=False, verbose_name='piano reduction'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='score',
            field=models.BooleanField(default=False, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='stitch_template',
            field=models.BooleanField(default=False, verbose_name='stitch template'),
        ),
    ]
