# Generated by Django 5.2.4 on 2026-07-23 12:15

import django.db.migrations.operations.special
from django.db import migrations, models

def migrate_function(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    for m in Manifestation.objects.filter(album_page = True).filter(is_singleton = True):
        item = m.items.first()
        item.album_page = True
        item.save()
    for m in Manifestation.objects.filter(performance_material = True).filter(is_singleton = True):
        item = m.items.first()
        item.performance_material = True
        item.save()
    for m in Manifestation.objects.filter(dedication_item = True).filter(is_singleton = True):
        item = m.items.first()
        item.dedication_item = True
        item.save()
    for m in Manifestation.objects.filter(correction_sheet = True).filter(is_singleton = True):
        item = m.items.first()
        item.correction_sheet = True
        item.save()
    for m in Manifestation.objects.filter(stitch_template = True).filter(is_singleton = True):
        item = m.items.first()
        item.stitch_template = True
        item.save()



# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dmrism.migrations.0007_migrate_function

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_item_source_type_alter_manifestation_source_type_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_stage',
            field=models.CharField(blank=True, choices=[('PR', 'print proof')], default=None, max_length=2, null=True, verbose_name='item stage'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('PR', 'manuscript proof')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
        migrations.AddField(
            model_name='item',
            name='album_page',
            field=models.BooleanField(default=False, verbose_name='album page'),
        ),
        migrations.AddField(
            model_name='item',
            name='correction_sheet',
            field=models.BooleanField(default=False, verbose_name='correction sheet'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedication_item',
            field=models.BooleanField(default=False, verbose_name='dedication item'),
        ),
        migrations.AddField(
            model_name='item',
            name='hand_copy',
            field=models.BooleanField(default=False, verbose_name='hand copy'),
        ),
        migrations.AddField(
            model_name='item',
            name='performance_material',
            field=models.BooleanField(default=False, verbose_name='performance material'),
        ),
        migrations.AddField(
            model_name='item',
            name='stitch_template',
            field=models.BooleanField(default=False, verbose_name='stitch template'),
        ),
        migrations.RunPython(
            code=migrate_function,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='album_page',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='correction_sheet',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='dedication_item',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='performance_material',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='stitch_template',
        ),
    ]
