# Generated by Django 5.2.4 on 2026-05-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_library_options'),
        ('dmrism', '0004_alter_manifestation_options'),
    ]

    operations = [
    ]
