# Generated by Django 5.2.4 on 2026-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_item_source_type_alter_manifestation_source_type_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_stage',
            field=models.CharField(blank=True, choices=[('PR', 'print proof')], default=None, max_length=2, null=True, verbose_name='item stage'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('PR', 'manuscript proof')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
