# Generated by Django 5.2.4 on 2025-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_remove_manifestation_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestationhandwriting',
            name='dubious_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifestationtitlehandwriting',
            name='dubious_writer',
            field=models.BooleanField(default=False),
        ),
    ]
