# Generated by Django 5.2.4 on 2026-05-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0002_remove_period_status'),
        ('dmrism', '0004_remove_manifestation_is_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmad.corporation', verbose_name='corporation'),
        ),
    ]
