# Generated by Django 5.2.4 on 2026-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_alter_corporationprovenancestation_period_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='personprovenancestationwebreference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
