# Generated by Django 5.2.4 on 2026-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_corporationprovenancestation_period_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='part_label',
            field=models.CharField(choices=[('l', 'logically and physically associated'), ('p', 'physically associated only'), ('f', 'formerly physically associated')], default='l', max_length=1, verbose_name='part label'),
        ),
        migrations.AlterField(
            model_name='corporationprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date')], default='per', max_length=3, verbose_name='period status'),
        ),
        migrations.AlterField(
            model_name='personprovenancestation',
            name='period_status',
            field=models.CharField(choices=[('acq', 'acquisition'), ('dis', 'disposition'), ('per', 'ownership period'), ('dat', 'ownership date')], default='per', max_length=3, verbose_name='period status'),
        ),
    ]
