# Generated by Django 5.2.4 on 2025-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0004_remove_manifestation_private_provenance_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='private_dedication_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
