# Generated by Django 5.2.4 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_manifestation_part_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='part_type',
            field=models.CharField(choices=[('c', 'constituting'), ('b', 'bound together'), ('s', 'separated')], default='c', max_length=1, verbose_name='part type'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to')], max_length=2, null=True, verbose_name='label'),
        ),
    ]
