# Generated by Django 5.2.4 on 2025-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_manifestationtitle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='dedication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
