# Generated by Django 5.2.4 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_alter_itemsignature_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
    ]
