# Generated by Django 5.2.4 on 2026-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_alter_item_item_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='album_page',
            field=models.BooleanField(default=False, verbose_name='album page'),
        ),
        migrations.AddField(
            model_name='item',
            name='correction_sheet',
            field=models.BooleanField(default=False, verbose_name='correction sheet'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedication_item',
            field=models.BooleanField(default=False, verbose_name='dedication item'),
        ),
        migrations.AddField(
            model_name='item',
            name='hand_copy',
            field=models.BooleanField(default=False, verbose_name='hand copy'),
        ),
        migrations.AddField(
            model_name='item',
            name='performance_material',
            field=models.BooleanField(default=False, verbose_name='performance material'),
        ),
        migrations.AddField(
            model_name='item',
            name='stitch_template',
            field=models.BooleanField(default=False, verbose_name='stitch template'),
        ),
    ]
