# Generated by Django 5.2.4 on 2026-06-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_transfer_completeness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='completeness',
        ),
    ]
