# Generated by Django 5.2.4 on 2026-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_alter_item_item_stage_and_more_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('PR', 'proof'), ('SK', 'sketch')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
