# Generated by Django 5.2.4 on 2026-02-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_manifestation_album_page_manifestation_choir_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='edition_type',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='function',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_manuscript_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private print comment'),
        ),
    ]
