# Generated by Django 5.2.4 on 2025-09-15 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0005_item_private_dedication_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_print_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_provenance_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='specific_figure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='stitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stitched_manifestations', to='dmad.corporation'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='function',
            field=models.CharField(blank=True, choices=[('COP', 'Copy'), ('ABP', 'Album Page'), ('PTE', 'Part Excerpt'), ('DDI', 'Dedication Item'), ('STT', 'Stitch Template'), ('CST', 'Corrected Stitch Template'), ('CRS', 'Correction Sheet')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_manifestations', to='dmad.corporation'),
        ),
    ]
