# Generated by Django 5.2.4 on 2026-07-03 08:15

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_alter_period_time_mode'),
        ('dmrism', '0005_alter_corporationprovenancestationwebreference_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='assumed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='inferred',
        ),
        migrations.AddField(
            model_name='item',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='is incomplete'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='edition_by_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='edition by source'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_partial_edition',
            field=models.BooleanField(default=False, verbose_name='partial edition'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='print_type',
            field=models.CharField(blank=True, choices=[('P', 'Plate Print'), ('L', 'Lithograph')], default=None, max_length=10, null=True, verbose_name='print type'),
        ),
        migrations.CreateModel(
            name='PublicationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='dmad.place')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_relations', to='dmrism.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
