# Generated by Django 5.2.4 on 2025-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_manifestationhandwriting_dubious_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='private_head_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_history_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_manuscript_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_provenance_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_relations_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='private_title_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='taken_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
