# Generated by Django 5.2.4 on 2025-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0005_alter_item_extent_alter_item_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sortier-Index'),
        ),
    ]
