# Generated by Django 5.2.4 on 2026-01-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0003_alter_period_status'),
        ('dmrism', '0005_alter_item_extent_alter_item_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='publication',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_manifestations', to='dmad.place'),
        ),
        migrations.AddField(
            model_name='publication',
            name='place_status',
            field=models.CharField(choices=[('D', 'documented'), ('I', 'inferred'), ('A', 'assumed')], default=None, max_length=1, null=True, verbose_name='title type'),
        ),
    ]
