# Generated by Django 5.2.4 on 2026-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_alter_manifestation_manifestation_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to'), ('RV', 'is revision of')], max_length=2, null=True, verbose_name='label'),
        ),
    ]
