# Generated by Django 5.2.4 on 2026-07-03 08:16

from django.db import migrations

def migrate_completeness(apps, schema_editor):
    Manifestation = apps.get_model('edwoca', 'manifestation')

    for m in Manifestation.objects.filter(is_singleton = True, is_incomplete = True):
        i = m.get_single_item()
        i.is_incomplete = True
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_remove_publication_assumed_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_completeness,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
