# Generated by Django 5.2.4 on 2026-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_alter_manifestation_manifestation_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to'), ('RV', 'is revision of')], max_length=2, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(blank=True, choices=[('EL', 'other title position'), ('HT', 'Head Title'), ('TP', 'Title Page'), ('EN', 'Envelope'), ('ET', 'Envelope or Title Page')], default=None, max_length=2, null=True, verbose_name='title type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='edition',
            field=models.CharField(blank=True, choices=[('1', 'first issue'), ('F', 'following issue')], default='F', max_length=10, null=True, verbose_name='edition'),
        ),
    ]
