# Generated by Django 5.2.4 on 2026-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_remove_publication_plate_number_publication_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='plate number'),
        ),
    ]
