# Generated by Django 5.2.4 on 2026-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0003_alter_library_options'),
        ('dmrism', '0006_alter_manifestation_first_save_and_more'),
    ]

    operations = [
    ]
