# Generated by Django 5.2.4 on 2026-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_manifestation_part_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='part_type',
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='part_label',
            field=models.CharField(choices=[('c', 'constituting'), ('b', 'bound together'), ('s', 'separated')], default='c', max_length=1, verbose_name='part label'),
        ),
    ]
