# Generated by Django 5.2.4 on 2026-07-22 14:04

from django.db import migrations

def migrate_function(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    for m in Manifestation.objects.filter(album_page = True).filter(is_singleton = True):
        item = m.items.first()
        item.album_page = True
        item.save()
    for m in Manifestation.objects.filter(performance_material = True).filter(is_singleton = True):
        item = m.items.first()
        item.performance_material = True
        item.save()
    for m in Manifestation.objects.filter(dedication_item = True).filter(is_singleton = True):
        item = m.items.first()
        item.dedication_item = True
        item.save()
    for m in Manifestation.objects.filter(correction_sheet = True).filter(is_singleton = True):
        item = m.items.first()
        item.correction_sheet = True
        item.save()
    for m in Manifestation.objects.filter(stitch_template = True).filter(is_singleton = True):
        item = m.items.first()
        item.stitch_template = True
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_item_album_page_item_correction_sheet_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_function,
            reverse_code=migrations.operations.special.RunPython.noop
        )
    ]
