# Generated by Django 5.2.4 on 2026-02-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_remove_manifestation_edition_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='private_manuscript_comment',
        ),
    ]
