# Generated by Django 5.2.4 on 2025-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_manifestation_print_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='private_provenance_comment',
        ),
        migrations.AddField(
            model_name='item',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
