# Generated by Django 5.2.4 on 2026-01-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_manifestation_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('P', 'is part of'), ('C', 'is component of'), ('A', 'has alternative')], max_length=10, null=True, verbose_name='label'),
        ),
    ]
