# Generated by Django 5.2.4 on 2026-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_alter_relatedmanifestation_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title_type',
            field=models.CharField(blank=True, choices=[('EL', 'other title position'), ('HT', 'Head Title'), ('TP', 'Title Page'), ('EN', 'Envelope'), ('ET', 'Envelope or Title Page')], default=None, max_length=2, null=True, verbose_name='title type'),
        ),
    ]
