# Generated by Django 5.2.4 on 2026-09-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0004_corporation_first_save_corporation_last_save_and_more'),
        ('dmrism', '0007_alter_relatedmanifestation_label_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='dmrism.manifestation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dmrism.item')),
                ('is_addition', models.BooleanField(default=False, verbose_name='addition')),
                ('is_correction', models.BooleanField(default=False, verbose_name='correction')),
                ('is_date_note', models.BooleanField(default=False, verbose_name='date note')),
                ('is_dedication', models.BooleanField(default=False, verbose_name='dedication')),
                ('is_note', models.BooleanField(default=False, verbose_name='note')),
                ('is_ownership_note', models.BooleanField(default=False, verbose_name='ownership note')),
                ('is_title', models.BooleanField(default=False, verbose_name='title')),
                ('description_title_correction', models.TextField(blank=True, null=True, verbose_name='description of title correction')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationHandwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='medium')),
                ('dubious_writer', models.BooleanField(default=False, verbose_name='dubious writer')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwritings', to='dmrism.annotation')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='history',
        ),
        migrations.AddField(
            model_name='item',
            name='date_diplomatic',
            field=models.TextField(blank=True, null=True, verbose_name='diplomatic date'),
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period'),
        ),
        migrations.AddField(
            model_name='item',
            name='private_history_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private dedication comment'),
        ),
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='places',
            field=models.ManyToManyField(through='dmrism.ItemPlace', to='dmad.place'),
        ),
    ]
