# Generated by Django 5.2.4 on 2025-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0031_remove_subjectterm_gnd_subject_category_and_more'),
        ('dmrism', '0007_remove_manifestation_private_provenance_comment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True)), fields=('manifestation',), name='unique_template_item_per_manifestation'),
        ),
    ]
