# Generated by Django 5.2.4 on 2026-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_remove_manifestation_private_manuscript_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='place_assumed',
            field=models.BooleanField(default=False, verbose_name='assumed'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='place_inferred',
            field=models.BooleanField(default=False, verbose_name='inferred'),
        ),
    ]
