# Generated by Django 5.2.4 on 2026-07-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_migrate_completeness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='is_incomplete',
        ),
    ]
