# Generated by Django 5.2.4 on 2026-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_remove_manifestation_part_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='part_label',
            field=models.CharField(choices=[('c', 'constituting'), ('b', 'bound together'), ('s', 'separated')], default=None, max_length=1, null=True, verbose_name='part label'),
        ),
    ]
