# Generated by Django 5.2.4 on 2026-07-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0007_migrate_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='album_page',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='correction_sheet',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='dedication_item',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='performance_material',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='stitch_template',
        ),
    ]
