# Generated by Django 5.2.4 on 2026-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0008_annotation_annotationhandwriting_squashed_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='edition',
            field=models.CharField(blank=True, choices=[('1', 'first issue'), ('F', 'following issue')], default=None, max_length=10, null=True, verbose_name='edition'),
        ),
    ]
