# Generated by Django 5.2.4 on 2026-08-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0008_annotation_annotationhandwriting'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_addition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_date_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_dedication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_ownership_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
    ]
