# Generated by Django 5.2.4 on 2026-01-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0008_alter_relatedmanifestation_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsignature',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='dmrism.library', verbose_name='holding institution'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('P', 'is part of'), ('C', 'is component of'), ('A', 'has alternative')], max_length=1, null=True, verbose_name='label'),
        ),
    ]
