# Generated by Django 5.2.4 on 2026-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0005_alter_period_time_mode'),
        ('dmrism', '0008_remove_manifestation_is_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='places',
            field=models.ManyToManyField(related_name='published_manifestations', through='dmrism.PublicationPlace', to='dmad.place'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.ManyToManyField(related_name='+', to='dmad.place'),
        ),
    ]
