# Generated by Django 5.2.4 on 2026-08-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0008_alter_manifestationtitle_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='edition',
            field=models.CharField(blank=True, choices=[('1', 'first issue'), ('F', 'following issue')], default='F', max_length=10, null=True, verbose_name='edition'),
        ),
    ]
