# Generated by Django 5.2.4 on 2025-09-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0008_item_unique_template_item_per_manifestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='paper',
        ),
    ]
