# Generated by Django 5.2.4 on 2026-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_annotation_is_addition_annotation_is_correction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationhandwriting',
            name='description_title_correction',
        ),
        migrations.AddField(
            model_name='annotation',
            name='description_title_correction',
            field=models.TextField(blank=True, null=True, verbose_name='description of title correction'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_addition',
            field=models.BooleanField(default=False, verbose_name='addition'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='corection'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_date_note',
            field=models.BooleanField(default=False, verbose_name='date note'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_dedication',
            field=models.BooleanField(default=False, verbose_name='dedication'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_note',
            field=models.BooleanField(default=False, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_ownership_note',
            field=models.BooleanField(default=False, verbose_name='ownership note'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_title',
            field=models.BooleanField(default=False, verbose_name='title'),
        ),
    ]
