# Generated by Django 5.2.4 on 2026-10-08 08:00

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


def migrate_edition(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    for manifestation in Manifestation.objects.all():
        if manifestation.items.count() == 1:
            single_item = manifestation.items.first()
            single_item.edition = single_item.manifestation.edition
            single_item.save()

def set_print_source_type(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    Manifestation.objects.filter(is_singleton = False, source_type__isnull = True).update(source_type = 'PRT')

def migrate_related_expression(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')
    RelatedExpression = apps.get_model('dmrism', 'relatedexpression')

    for manifestation in Manifestation.objects.all():
        if manifestation.working_title:
            RelatedExpression.objects.create(
                    manifestation = manifestation,
                    working_title = manifestation.working_title
                )


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_alter_manifestation_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_title', models.TextField(blank=True, null=True, verbose_name='working title')),
                ('manifestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expression_relations', to='dmrism.manifestation')),
            ],
        ),
        migrations.RunPython(
            code=migrate_related_expression,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=set_print_source_type,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='manifestation',
            name='without_proof_copy',
            field=models.BooleanField(default=False, verbose_name='without proof copy'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='collection_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='dmrism.relatedexpression'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to')], max_length=2, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='item',
            name='edition',
            field=models.CharField(blank=True, choices=[('1', 'first issue'), ('F', 'following issue')], default=None, max_length=10, null=True, verbose_name='edition'),
        ),
        migrations.RunPython(
            code=migrate_edition,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='working_title',
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to'), ('D', 'is derivative of')], max_length=2, null=True, verbose_name='label'),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_date_note',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_dedication',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_ownership_note',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_stage',
        ),
        migrations.AddField(
            model_name='manifestationtitle',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
