# Generated by Django 5.2.4 on 2026-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_alter_itemsignature_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='private_dedication_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private dedication comment'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='edition_type',
            field=models.CharField(blank=True, choices=[('CSC', 'Choir Score'), ('PNR', 'Piano Reduction'), ('PTC', 'Particell'), ('SCO', 'Score'), ('PTS', 'Parts')], default=None, max_length=10, null=True, verbose_name='edition type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='function',
            field=models.CharField(blank=True, choices=[('ABP', 'Album Page'), ('PFM', 'Performance Material'), ('CRS', 'Correction Sheet'), ('STT', 'Stitch Template'), ('DDI', 'Dedication Item')], default=None, max_length=5, null=True, verbose_name='function'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('EX', 'Excerpts'), ('SK', 'Sketches'), ('FR', 'Fragments')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
