# Generated by Django 5.2.4 on 2026-09-25 13:38

import django.db.models.deletion
from django.db import migrations, models
import django.db.migrations.operations.special

def set_print_source_type(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    Manifestation.objects.filter(is_singleton = False, source_type__isnull = True).update(source_type = 'PRT')

def migrate_related_expression(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')
    RelatedExpression = apps.get_model('dmrism', 'relatedexpression')

    for manifestation in Manifestation.objects.all():
        if manifestation.working_title:
            RelatedExpression.objects.create(
                    manifestation = manifestation,
                    working_title = manifestation.working_title
                )

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_alter_manifestation_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_title', models.TextField(blank=True, null=True, verbose_name='working title')),
                ('manifestation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expression_relations', to='dmrism.manifestation')),
            ],
        ),
        migrations.RunPython(
            code=migrate_related_expression,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=set_print_source_type,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
