# Generated by Django 5.2.4 on 2026-07-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0009_publication_places_alter_publication_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='place',
        ),
    ]
