# Generated by Django 5.2.4 on 2026-09-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmad', '0004_corporation_first_save_corporation_last_save_and_more'),
        ('dmrism', '0008_annotation_annotationhandwriting_squashed_0010_remove_annotationhandwriting_description_title_correction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='history',
        ),
        migrations.AddField(
            model_name='item',
            name='date_diplomatic',
            field=models.TextField(blank=True, null=True, verbose_name='private dedication comment'),
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmad.period'),
        ),
        migrations.AddField(
            model_name='item',
            name='private_history_comment',
            field=models.TextField(blank=True, null=True, verbose_name='private dedication comment'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='correction'),
        ),
        migrations.CreateModel(
            name='ItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False, verbose_name='inferred')),
                ('assumed', models.BooleanField(default=False, verbose_name='assumed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmrism.item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmad.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='places',
            field=models.ManyToManyField(through='dmrism.ItemPlace', to='dmad.place'),
        ),
    ]
