# Generated by Django 5.2.4 on 2026-10-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0010_relatedexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='without_proof_copy',
            field=models.BooleanField(default=False, verbose_name='without proof copy'),
        ),
    ]
