# Generated by Django 5.2.4 on 2026-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0011_remove_manifestation_history_item_date_diplomatic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_diplomatic',
            field=models.TextField(blank=True, null=True, verbose_name='diplomatic date'),
        ),
    ]
