# Generated by Django 5.2.4 on 2026-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0011_remove_publication_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='is_explanation',
            field=models.BooleanField(default=False, verbose_name='is explanation'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_lyrics',
            field=models.BooleanField(default=False, verbose_name='is lyrics'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='is_program',
            field=models.BooleanField(default=False, verbose_name='is program'),
        ),
    ]
