# Generated by Django 5.2.4 on 2026-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0011_alter_manifestation_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestationtitle',
            name='status',
        ),
        migrations.AddField(
            model_name='manifestation',
            name='source_title',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='source title'),
        ),
        migrations.AddField(
            model_name='manifestation',
            name='working_title',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='working title'),
        ),
    ]
