# Generated by Django 5.2.4 on 2026-10-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0011_manifestation_without_proof_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='collection_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='dmrism.relatedexpression'),
        ),
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to')], max_length=2, null=True, verbose_name='label'),
        ),
    ]
