# Generated by Django 5.2.4 on 2026-10-02 07:30

from django.db import migrations, models
import django.db.migrations.operations.special

def migrate_edition(apps, schema_editor):
    Manifestation = apps.get_model('dmrism', 'manifestation')

    for manifestation in Manifestation.objects.all():
        if manifestation.items.count() == 1:
            single_item = manifestation.items.first()
            single_item.edition = single_item.manifestation.edition
            single_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0012_alter_annotation_collection_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='edition',
            field=models.CharField(blank=True, choices=[('1', 'first issue'), ('F', 'following issue')], default=None, max_length=10, null=True, verbose_name='edition'),
        ),
        migrations.RunPython(
            code=migrate_edition,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
