# Generated by Django 5.2.4 on 2026-07-06 14:37

from django.db import migrations

def migrate_text_types(apps, schema_editor):
    Item = apps.get_model('edwoca', 'item')

    for i in Item.objects.filter(manifestation__is_singleton=True):
        for prop in ['is_lyrics', 'is_program', 'is_explanation']:
            if getattr(i, prop):
                setattr(i.manifestation, prop, True)
                setattr(i, prop, False)
        i.manifestation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0012_manifestation_is_explanation_manifestation_is_lyrics_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_text_types,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
    ]
