# Generated by Django 5.2.4 on 2026-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0012_remove_manifestationtitle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestationtitle',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='diplomatic title'),
        ),
    ]
