# Generated by Django 5.2.4 on 2026-01-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0006_alter_item_order_index'),
        ('dmrism', '0013_alter_manifestationtitle_title'),
    ]

    operations = [
    ]
