# Generated by Django 5.2.4 on 2026-10-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0013_item_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='working_title',
        ),
    ]
