# Generated by Django 5.2.4 on 2026-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0013_migrate_text_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='title_page',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='title page diplomatic'),
        ),
    ]
