# Generated by Django 5.2.4 on 2026-01-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0014_merge_20260116_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='dedicatees',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='dedication',
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='plate_number',
        ),
    ]
