# Generated by Django 5.2.4 on 2026-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0014_manifestation_title_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-needs_review', 'manifestation', 'order_index']},
        ),
        migrations.RemoveField(
            model_name='manifestation',
            name='proof',
        ),
        migrations.AddField(
            model_name='item',
            name='editing_history',
            field=models.TextField(blank=True, default='', verbose_name='editing history'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_editor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='first editor'),
        ),
        migrations.AddField(
            model_name='item',
            name='first_save',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='first save'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_save',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last save'),
        ),
        migrations.AddField(
            model_name='item',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='manifestation_form',
            field=models.CharField(blank=True, choices=[('SK', 'Sketches'), ('PR', 'proof')], default=None, max_length=10, null=True, verbose_name='manifestation form'),
        ),
    ]
