# Generated by Django 5.2.4 on 2026-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0014_remove_manifestation_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmanifestation',
            name='label',
            field=models.CharField(choices=[('SD', 'is stitch template (as documented)'), ('SI', 'is stitch template (inferred)'), ('R', 'is related to'), ('D', 'is derivative of')], max_length=2, null=True, verbose_name='label'),
        ),
    ]
