# Generated by Django 5.2.4 on 2026-07-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
        ('dmrism', '0003_alter_corporationprovenancestation_period_status_and_more_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='source_title',
            field=models.TextField(blank=True, default='', verbose_name='source title'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('TSC', 'transcript'), ('CTS', 'transcript with autograph entries'), ('AUT', 'autograph'), ('QAU', 'questionable autograph'), ('CPR', 'print with autograph entries'), ('PRT', 'print')], default='AUT', max_length=5, null=True, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='title_page',
            field=models.TextField(blank=True, default='', verbose_name='title page diplomatic'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='working_title',
            field=models.TextField(blank=True, default='', verbose_name='working title'),
        ),
        migrations.CreateModel(
            name='ItemBib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='bib location')),
                ('location_type', models.CharField(choices=[('P', 'page'), ('C', 'column'), ('L', 'lot')], default='P', max_length=1, verbose_name='bib location type')),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bib.zotitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bib_set', to='dmrism.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
