# Generated by Django 5.2.4 on 2026-10-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0015_alter_relatedmanifestation_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_date_note',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_dedication',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='is_ownership_note',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_stage',
        ),
    ]
