# Generated by Django 5.2.4 on 2026-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmrism', '0016_alter_itemcorporationdedication_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='plate number'),
        ),
    ]
