from django.urls import path
from .. import views

urlpatterns = [
    path('', views.WorkListView.as_view(), name = 'work_list'),
    path('search', views.WorkSearchView.as_view(), name = 'work_search'),
    path('new', views.work_create, name = 'work_create'),
    path('<int:pk>/createexpression', views.work_expression_create, name = 'expression_create'),
    path('<int:pk>/update', views.WorkTitleUpdateView.as_view(), name = 'work_update'),
    path('<int:pk>/detail', views.WorkDetailView.as_view(), name = 'work_detail'),
    path('<int:pk>/relations', views.WorkRelationsUpdateView.as_view(), name = 'work_relations'),
    path('<int:pk>/relations/addrelatedwork/<int:target_related_work>', views.RelatedWorkAddView.as_view(), name = 'related_work_add'),
    path('removerelatedwork/<int:pk>', views.RelatedWorkRemoveView.as_view(), name = 'related_work_remove'),
    path('<int:pk>/references', views.WorkReferencesUpdateView.as_view(), name = 'work_references'),
    path('<int:pk>/references/addreferencework/<int:target_reference_work>', views.reference_work_add, name = 'reference_work_add'),
    path('removereferencework/<int:pk>', views.ReferenceWorkRemoveView.as_view(), name = 'reference_work_remove'),
    path('<int:pk>/references/addreferenceperson/<int:target_reference_person>', views.reference_person_add, name = 'reference_person_add'),
    path('removereferenceperson/<int:pk>', views.ReferencePersonRemoveView.as_view(), name = 'reference_person_remove'),
    path('<int:pk>/references/addreferencecorporation/<int:target_reference_corporation>', views.reference_corporation_add, name = 'reference_corporation_add'),
    path('removereferencecorporation/<int:pk>', views.ReferenceCorporationRemoveView.as_view(), name = 'reference_corporation_remove'),
    path('<int:pk>/references/addreferenceplace/<int:target_reference_place>', views.reference_place_add, name = 'reference_place_add'),
    path('removereferenceplace/<int:pk>', views.ReferencePlaceRemoveView.as_view(), name = 'reference_place_remove'),
    path('<int:pk>/references/addreferencesubjectterm/<int:target_reference_subjectterm>', views.reference_subjectterm_add, name = 'reference_subjectterm_add'),
    path('removereferencesubjectterm/<int:pk>', views.ReferenceSubjectTermRemoveView.as_view(), name = 'reference_subjectterm_remove'),
    path('<int:pk>/title', views.WorkTitleUpdateView.as_view(), name = 'work_title'),
    path('person_dedication/add/<int:pk>/', views.work_person_dedication_add, name='work_person_dedication_add'),
    path('corporation_dedication/add/<int:pk>/', views.work_corporation_dedication_add, name='work_corporation_dedication_add'),
    path('person_dedication/delete/<int:pk>/', views.work_person_dedication_delete, name='work_person_dedication_delete'),
    path('corporation_dedication/delete/<int:pk>/', views.work_corporation_dedication_delete, name='work_corporation_dedication_delete'),
    path('<int:pk>/person_dedication/<int:dedication_id>/add_dedicatee/<int:person_id>/', views.work_person_dedication_add_dedicatee, name='work_person_dedication_add_dedicatee'),
    path('<int:pk>/person_dedication/<int:dedication_id>/remove_dedicatee/', views.work_person_dedication_remove_dedicatee, name='work_person_dedication_remove_dedicatee'),
    path('<int:pk>/corporation_dedication/<int:dedication_id>/add_dedicatee/<int:corporation_id>/', views.work_corporation_dedication_add_dedicatee, name='work_corporation_dedication_add_dedicatee'),
    path('<int:pk>/corporation_dedication/<int:dedication_id>/remove_dedicatee/', views.work_corporation_dedication_remove_dedicatee, name='work_corporation_dedication_remove_dedicatee'),
    path('<int:pk>/dedication/<int:dedication_id>/add_place/<int:place_id>/', views.work_dedication_add_place, name='work_dedication_add_place'),
    path('<int:pk>/dedication/<int:dedication_id>/remove_place/', views.work_dedication_remove_place, name='work_dedication_remove_place'),
    path('<int:pk>/contributors', views.WorkContributorsUpdateView.as_view(), name = 'work_contributors'),
    path('<int:pk>/contributors/addcontributor/<int:person>', views.WorkContributorAddView.as_view(), name = 'work_contributor_add'),
    path('removecontributor/<int:pk>', views.WorkContributorRemoveView.as_view(), name = 'work_contributor_remove'),
    path('<int:pk>/history', views.WorkHistoryUpdateView.as_view(), name = 'work_history'),
    path('<int:pk>/bibliography', views.WorkBibliographyUpdateView.as_view(), name = 'work_bibliography'),
    path('<int:pk>/bibliography/addbib/<str:zotitem_key>', views.WorkBibAddView.as_view(), name = 'work_bib_add'),
    path('removebib/<int:pk>', views.WorkBibDeleteView.as_view(), name = 'work_bib_remove'),
    path('<int:pk>/letteradd/<int:letter_pk>', views.work_letter_add, name = 'work_letter_add'),
    path('<int:pk>/letterremove/<int:letter_pk>', views.work_letter_remove, name = 'work_letter_remove'),
    path('<int:pk>/comment', views.WorkCommentUpdateView.as_view(), name = 'work_comment'),
    path('<int:pk>/head_comment', views.WorkHeadCommentUpdateView.as_view(), name = 'work_head_comment'),
    path('<int:pk>/delete', views.WorkDeleteView.as_view(), name = 'work_delete'),
]
